import {createModules} from './modules.js';
import {Repository} from './repository.js';
const api=new Repository();
const $=s=>document.querySelector(s),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>x==null?'—':Number(x).toLocaleString('hu-HU',{maximumFractionDigits:1});
const dt=x=>x?new Date(x.length===10?x+'T12:00:00':x).toLocaleDateString('hu-HU'):'Nincs adat';
const categories={free_weight:'Szabad súly',machine:'Gép',bodyweight:'Saját testsúly',cardio:'Kardió'};
const pages=[['profile','Adatlap'],['daily','Napi napló'],['weekly','Heti összesítő'],['workouts','Edzésnapló'],['diet','Étrend'],['food','Kajanapló'],['medication','Gyógyszer'],['measurements','Mérések'],['photos','Fotónapló'],['settings','Beállítások']];
let user=null,clients=[],client=null,today='',page='profile',setupRequired=false,waitingUpdate=null,exercises=[],plans=[],workouts=[],rests=[],activeWorkout=null,builder=null,records=[],noteRows=[],foodRows=[],measurementRows=[],dailyRows=[],renderId=0,toastTimer;
const paths={clients:'M4 20v-2a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v2 M14 4a4 4 0 0 1 0 8 M19 14a4 4 0 0 1 3 4 M10 3a4 4 0 1 0 0 8',profile:'M5 20v-2a5 5 0 0 1 5-5h4a5 5 0 0 1 5 5v2 M12 3a4 4 0 1 0 0 8',daily:'M8 3v4 M16 3v4 M3 9h18 M5 5h14v16H5z M8 13h3 M8 17h7',weekly:'M4 20V4 M4 20h17 M8 15v-4 M13 15V7 M18 15v-6',workouts:'M2 8v8 M5 6v12 M5 12h14 M19 6v12 M22 8v8',diet:'M4 3v6a3 3 0 0 0 6 0V3 M7 3v18 M17 3v18 M17 3c4 2 4 9 0 9',food:'M4 8h16 M3 8a9 9 0 0 0 18 0 M7 4v1 M12 3v2 M17 4v1',medication:'M7 17l10-10 M5 19a5 5 0 0 1 0-7l7-7a5 5 0 0 1 7 7l-7 7a5 5 0 0 1-7 0',measurements:'M3 8h18v12H3z M6 8v5 M10 8v3 M14 8v5 M18 8v3',photos:'M3 6h5l2-3h4l2 3h5v15H3z M12 9a4 4 0 1 0 0 8',settings:'M12 8a4 4 0 1 0 0 8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',exercises:'M4 4h16v16H4z M8 8h8 M8 12h8 M8 16h5'};
const icon=(name='workouts')=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.workouts}"/></svg>`;
const button=(action,label,attrs='',primary=false)=>{const custom=attrs.match(/class="([^"]*)"/)?.[1]||'';return `<button type="button" data-action="${action}" ${attrs.replace(/class="[^"]*"/,'')} class="${primary?'primary ':''}${custom}">${label}</button>`;};
const input=(name,label,value='',type='text',attrs='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
const textarea=(name,label,value='',attrs='')=>`<label>${label}<textarea name="${name}" ${attrs}>${esc(value)}</textarea></label>`;
const field=(name,label,value='',min=0,max=1000,required=false)=>input(name,label,value??'','number',`min="${min}" max="${max}" step="any" inputmode="decimal" ${required?'required':''}`);
const check=(name,label,value=false)=>`<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${label}</label>`;
const empty=(title,text,action='',label='')=>`<div class="empty">${icon(page)}<h2>${title}</h2><p>${text}</p>${action?button(action,label,'',true):''}</div>`;
const metric=(label,value,unit='',sub='')=>`<div class="metric"><div class="label">${label}</div><div class="value">${esc(value)}<span class="unit">${unit}</span></div>${sub?`<div class="sub">${sub}</div>`:''}</div>`;
const initials=name=>esc(name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase());
const coach=()=>['coach','admin'].includes(user?.role);
const writable=()=>!client?.archived_at;
const factWriter=()=>user?.role==='client'&&writable();
const endpoint=resource=>`/clients/${client.id}${resource?'/'+resource:''}`;
function monday(d){const v=new Date(d+'T12:00:00Z'),n=v.getUTCDay();v.setUTCDate(v.getUTCDate()-(n===0?6:n-1));return v.toISOString().slice(0,10);}
function shift(d,n){const v=new Date(d+'T12:00:00Z');v.setUTCDate(v.getUTCDate()+n);return v.toISOString().slice(0,10);}
function avatar(c,big=false){return c.has_avatar?`<img class="avatar ${big?'profile-avatar':''}" src="/api/v1/clients/${c.id}/avatar?v=${c.version}" alt="${esc(c.name)} profilképe">`:`<div class="avatar ${big?'profile-avatar':''}" aria-hidden="true">${initials(c.name)}</div>`;}
function toast(message,error=false){clearTimeout(toastTimer);const el=$('#toast');el.textContent=message;el.className=error?'error':'';el.style.display='block';toastTimer=setTimeout(()=>{el.style.display='none';},error?9000:3500);}
function hasUnsaved(){return [...document.querySelectorAll('form[data-dirty="true"]')].some(f=>f.closest('dialog')?f.closest('dialog').open:true);}
function route(next,id){if(hasUnsaved()&&!confirm('Van még nem mentett adatbevitel. Elhagyod az oldalt?'))return;const params=new URLSearchParams();if(id||client?.id)params.set('client',id||client.id);const hash=`#/${next}${params.size?'?'+params:''}`;if(location.hash===hash)refresh();else location.hash=hash;}
function head(title,text,actions=''){return `<div class="page-head"><div><div class="eyebrow">${coach()?'Edzői munkaterület':'Személyes sportlabor'}</div><h1>${title}</h1><p>${text}</p></div><div class="row">${actions}</div></div>`;}
function formFooter(label='Mentés'){return `<div class="form-error" role="alert"></div><div class="form-actions">${button('close-dialog','Mégse')}<button class="primary" type="submit">${label}</button></div>`;}
function dialog(title,html){const el=$('#dialog');el.innerHTML=`<div class="dialog-head"><div><div class="eyebrow">IMPAVIDUS LAB</div><h2 id="dialog-title">${title}</h2></div>${button('close-dialog','×','aria-label="Bezárás"')}</div>${html}`;if(!el.open)el.showModal();}
function authView(){
  const setup=setupRequired;
  $('#app').innerHTML=`<div class="auth"><div class="auth-card"><div class="brand"><img src="/icon.svg" alt=""><div class="brand-name">IMPAVIDUS LAB</div></div><div class="eyebrow">Precíz munka. Valós eredmények.</div><h1>${setup?'A munkaterület megnyitása':'Üdv újra a laborban'}</h1><p class="muted">${setup?'Hozd létre az első edzői fiókot.':'Lépj be az edzésterveidhez és a naplóidhoz.'}</p><form data-form="auth" data-mode="${setup?'setup':'login'}">${input('username','Felhasználónév','','text','required minlength="3" maxlength="254" autocomplete="username" autocapitalize="none" spellcheck="false"')}${input('password','Jelszó','','password',`required minlength="12" maxlength="128" autocomplete="${setup?'new-password':'current-password'}"`)}${setup?'<p class="help">A jelszó legalább 12 karakter hosszú legyen.</p>':''}<div class="form-error" role="alert"></div><button class="primary full" type="submit">${setup?'Edzői fiók létrehozása':'Belépés'}</button></form><div class="separator"></div><p class="help">Adatmentés a szerveren. Bejelentkezés után a naplóadatok helyben is menthetők. A függő változások kapcsolódáskor szinkronizálódnak.</p></div></div>`;
}
function shell(){
  const options=clients.filter(c=>!c.archived_at||c.id===client?.id).map(c=>`<option value="${c.id}" ${c.id===client?.id?'selected':''}>${esc(c.name)}</option>`).join('');
  $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="/icon.svg" alt=""><div class="brand-name">IMPAVIDUS LAB</div></div><nav class="nav" aria-label="Fő navigáció">${coach()?`<div class="nav-label">MUNKATERÜLET</div><a href="#/clients" class="${page==='clients'?'active':''}">${icon('clients')}Kliensek</a><a href="#/exercises" class="${page==='exercises'?'active':''}">${icon('exercises')}Gyakorlatok</a>`:''}<div class="nav-label">${client?esc(client.name):'KLIENSMODULOK'}</div>${pages.map(([id,label])=>`<a href="#/${id}${client?'?client='+client.id:''}" ${page===id?'aria-current="page"':''} class="${page===id?'active':''}">${icon(id)}${label}</a>`).join('')}</nav><div class="sidebar-foot"><div><span class="dot"></span>Adattár és helyi mentések</div><div class="help">${esc(user.username)}</div>${button('logout','Kijelentkezés')}</div></aside><div class="workspace"><header class="topbar"><div class="row">${button('menu','Menü','class="mobile-menu" aria-label="Navigáció megnyitása" aria-expanded="false"')}<span class="mobile-brand">IMPAVIDUS LAB</span><span class="desktop-only muted">${coach()?'Edzői labor':'Sportolói munkatér'}</span></div><div class="identity">${coach()&&clients.length?`<select class="client-switch" aria-label="Aktív kliens">${options}</select>`:''}<div class="initials">${coach()?initials(user.username):initials(client?.name||'Kliens')}</div><span class="role desktop-only">${coach()?'Edző':'Kliens'}</span></div></header><main class="content" id="content" tabindex="-1"><div class="loading" role="status">Adatok betöltése…</div></main></div></div>`;
}
async function refresh(){
  const sequence=++renderId;
  try {
    const session=await api.request('/auth/session');today=session.today;setupRequired=session.setupRequired;user=session.user;api.csrf=user?.csrf||null;
    if(!user){authView();return;}
    clients=await api.request('/clients');
    const parsed=new URL(location.hash.slice(1)||'/'+(coach()?'clients':'profile'),'https://local');page=parsed.pathname.slice(1)||'profile';
    if(!['clients','exercises',...pages.map(x=>x[0])].includes(page)||(page==='clients'||page==='exercises')&&!coach())page='profile';
    const requested=parsed.searchParams.get('client');client=clients.find(c=>c.id===requested)||clients.find(c=>!c.archived_at)||clients[0]||null;
    if(sequence!==renderId)return;shell();
    let content;
    const moduleContent=await modules.page(page,parsed);
    if(moduleContent!==null)content=moduleContent;
    else if(page==='clients')content=clientsPage();
    else if(page==='exercises'){exercises=await api.request('/exercises');content=exercisesPage();}
    else if(page==='settings')content=settingsPage();
    else if(!client)content=head('Munkaterület','A kliensmodulok megnyitásához hozz létre egy sportolói profilt.')+empty('Még nincs kliens','Az első profil létrehozása után hozzárendelhetsz egy edzéstervet.','new-client','Új kliens');
    else if(page==='profile'){noteRows=await api.request(endpoint('notes'));content=profilePage();}
    else if(page==='workouts'){[plans,workouts,rests,exercises]=await Promise.all([api.request(endpoint('plans')),api.request(endpoint('workouts')),api.request(endpoint('rest-days')),api.request('/exercises')]);activeWorkout=activeWorkout&&workouts.find(w=>w.id===activeWorkout.id)?await api.request(endpoint('workouts/'+activeWorkout.id)):null;content=workoutPage();}
    else if(page==='weekly'){const week=parsed.searchParams.get('week')||monday(today);content=await weeklyPage(week);}
    else if(page==='measurements'){measurementRows=await api.request(endpoint('measurements'));content=measurementsPage();}
    else if(page==='food'){foodRows=await api.request(endpoint('food-logs'));content=foodPage();}
    else if(page==='daily'){[dailyRows,foodRows,workouts,rests]=await Promise.all(['daily-logs','food-logs','workouts','rest-days'].map(x=>api.request(endpoint(x))));content=dailyPage();}
    else {const kind={diet:'diet',medication:'medication',photos:'photo'}[page];records=await api.request(endpoint('records')+'?kind='+kind);content=recordsPage(kind);}
    if(sequence!==renderId)return;$('#content').innerHTML=content;
    const sync=await api.syncStatus();$('.workspace').insertAdjacentHTML('afterbegin',`<div class="sync-banner" role="status">${sync.online?'Kapcsolat a szerverrel':'Offline · helyi adattár'} · ${sync.pending} mentés vár szinkronra${sync.conflicts?' · '+sync.conflicts+' rendezendő ütközés':''}</div>`);
    if(client)api.prime(client).catch(()=>{});
    showUpdate();
    if(client?.metrics?.weight_date&&shift(client.metrics.weight_date,7)<today&&page==='profile')$('#content').insertAdjacentHTML('afterbegin','<div class="notice">Az utolsó testsúlymérés több mint hét napja történt.</div>');
    if(client?.archived_at)$('#content').insertAdjacentHTML('afterbegin','<div class="notice">Archivált kliens · az adatok megmaradtak, a profil csak olvasható.</div>');
  }catch(e){if(e.status===401){user=null;authView();}else{toast(e.message,true);const main=$('#content');if(main)main.innerHTML=empty('Nem sikerült betölteni az adatokat',esc(e.message),'retry','Újrapróbálás');else $('#app').innerHTML=`<main class="auth">${empty('Az alkalmazás nem érhető el',esc(e.message),'retry','Újrapróbálás')}</main>`;}}
}
function clientsPage(){return head('A csapat','Minden sportoló, egy munkatérben. Kizárólag a hozzád rendelt profilok láthatók.',button('new-client','+ Új kliens','',true))+`<div class="toolbar"><input id="client-search" type="search" placeholder="Keresés név alapján…" aria-label="Kliens keresése"><label class="check"><input id="show-archived" type="checkbox">Archiváltak is</label></div><div class="cards" id="client-cards">${clients.length?clients.map(c=>{const m=c.metrics;return `<article class="card client-card ${c.archived_at?'archive':''}" data-client-card data-name="${esc(c.name.toLowerCase())}" data-archived="${!!c.archived_at}" ${c.archived_at?'hidden':''}><div class="client-head">${avatar(c)}<div><h3>${esc(c.name)}</h3><span class="muted">${esc(c.phase||'Fázis nincs megadva')}</span>${c.archived_at?'<br><span class="badge">Archivált</span>':''}</div></div><dl><div><dt>Aktuális testsúly</dt><dd>${m.current_weight==null?'Nincs mérés':num(m.current_weight)+' kg'}</dd></div><div><dt>Heti teljesített nap</dt><dd>${m.activity.weekly} / 7</dd></div><div><dt>Utolsó aktivitás</dt><dd>${dt(m.last_activity)}</dd></div><div><dt>Aktuális terv</dt><dd>${esc(m.current_plan?.name||'Nincs terv')}</dd></div></dl>${button('open-client','Profil megnyitása',`data-id="${c.id}" class="full"`)}</article>`;}).join(''):empty('A csapat még üres','Hozz létre egy klienst, majd készíts neki személyre szabott edzéstervet.','new-client','Első kliens létrehozása')}</div><p id="client-no-results" class="muted" hidden>Nincs a keresésnek megfelelő kliens.</p>`;}
function profilePage(){const m=client.metrics;return `<div class="page-head"><div class="profile-title">${avatar(client,true)}<div><div class="eyebrow">Sportolói adatlap</div><h1>${esc(client.name)}</h1><span class="muted">${esc(client.phase||'Fázis nincs megadva')} · Kezdés: ${dt(client.start_date)}</span></div></div><div class="row">${coach()&&writable()?button('edit-client','Adatlap szerkesztése'):''}${writable()?button('avatar','Profilkép'):''}${coach()?button(client.archived_at?'restore-client':'archive-client',client.archived_at?'Visszaállítás':'Archiválás'):''}</div></div><div class="metrics">${metric('Aktuális testsúly',num(m.current_weight),'kg',m.weight_date?'Mérés: '+dt(m.weight_date):'Még nincs rögzített mérés')}${metric('Súlyváltozás',num(m.weight_delta),'kg',m.weight_percent==null?'Kezdősúly és mérés szükséges':num(m.weight_percent)+'% az induláshoz képest')}${metric('Aktuális sorozat',num(m.activity.current),'nap','Kajanapló + edzés / pihenőnap')}${metric('Leghosszabb sorozat',num(m.activity.longest),'nap',m.activity.weekly+' teljesített nap ezen a héten')}</div><div class="grid"><section class="card"><div class="eyebrow">Kiindulópont</div><h2>A sportoló profilja</h2><dl class="detail-list"><div><dt>Kezdősúly</dt><dd>${num(client.starting_weight)} kg</dd></div><div><dt>Magasság</dt><dd>${num(client.height)} cm</dd></div><div><dt>Célsúly</dt><dd>${num(client.target_weight)} kg</dd></div><div><dt>Aktuális edzésterv</dt><dd>${esc(m.current_plan?.name||'Még nincs terv')}</dd></div><div class="span"><dt>Cél</dt><dd>${esc(client.goal||'Nincs megadva')}</dd></div></dl>${button('go-workouts','Edzéstervek és napló megnyitása','',true)}</section><section class="card"><div class="eyebrow">Fejlődés</div><h2>Edzői megjegyzések</h2>${noteRows.length?noteRows.map(n=>`<div class="list-row"><div><div class="muted">${dt(n.created_at)}</div><p class="note">${esc(n.text)}</p></div>${coach()&&writable()?button('archive-note','Archiválás',`data-id="${n.id}"`):''}</div>`).join(''):'<p class="muted">Még nincs fejlődési megjegyzés.</p>'}${coach()&&writable()?button('new-note','+ Megjegyzés'):''}<div class="separator"></div><p class="help">Egy teljesített naphoz kajanapló és rögzített tényleges edzés vagy explicit pihenőnap szükséges. Egy hiányzó nap hetente megengedett.</p>${coach()&&writable()?button('account-access','Belépési adatok'):''}</section></div>`;}
function profileForm(c={}){dialog(c.id?'Adatlap szerkesztése':'Új kliens',`<form data-form="client" data-id="${c.id||''}"><div class="form-grid">${input('name','Teljes név',c.name||'','text','required maxlength="120"')}${input('start_date','Kezdési dátum',c.start_date||today,'date',`required max="${today}" min="2000-01-01"`)}${field('starting_weight','Kezdősúly (kg)',c.starting_weight,20,500)}${field('height','Magasság (cm)',c.height,80,250)}${field('target_weight','Célsúly (kg) · opcionális',c.target_weight,20,500)}${input('phase','Aktuális ciklus / fázis',c.phase||'','text','maxlength="120"')}<div class="span">${textarea('goal','Cél',c.goal||'','maxlength="2000"')}</div></div>${!c.id?`<div class="separator"></div><h3>Kliens belépési adatai</h3><div class="form-grid">${input('username','Felhasználónév','','text','required minlength="3" maxlength="254" autocomplete="off" autocapitalize="none" spellcheck="false"')}${input('password','Jelszó','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}</div><p class="help">A jelszó legalább 12 karakter. A kliens ezekkel az adatokkal léphet be.</p>`:''}${formFooter(c.id?'Módosítások mentése':'Kliens létrehozása')}</form>`);}
function exercisesPage(){return head('Gyakorlatkönyvtár','Egy központi katalógus az edzéstervekhez. Az inaktív gyakorlatok a korábbi naplókban megmaradnak.',button('new-exercise','+ Új gyakorlat','',true))+`<div class="toolbar"><input id="exercise-search" type="search" placeholder="Név, izomcsoport vagy eszköz…" aria-label="Gyakorlat keresése">${button('import-exercises','Licencelt JSON import')}</div><section class="card">${exercises.length?exercises.map(e=>`<div class="list-row" data-exercise-row data-search="${esc((e.name+' '+e.muscle+' '+e.equipment).toLowerCase())}"><div><h3>${esc(e.name)}</h3><div class="muted">${esc(e.muscle)} · ${esc(e.equipment)} · ${categories[e.category]} ${!e.active?'· Inaktív':''}</div>${e.source?`<div class="help">Forrás: ${esc(e.source)}${e.version>1?' · IMPAVIDUS LAB-ban módosított adat':''} · ${esc(e.license)} · ${esc(e.author)} · <a href="${esc(e.source_url)}" rel="noopener noreferrer" target="_blank">Eredeti adat</a></div>`:''}</div><div class="actions">${button('edit-exercise','Szerkesztés',`data-id="${e.id}"`)}${button('toggle-exercise',e.active?'Inaktiválás':'Aktiválás',`data-id="${e.id}"`)}</div></div>`).join(''):empty('A könyvtár még üres','Hozz létre saját gyakorlatokat vagy importálj ellenőrzött, megfelelő licencű adatokat.','new-exercise','Gyakorlat létrehozása')}</section>`;}
function exerciseForm(e={}){dialog(e.id?'Gyakorlat szerkesztése':'Új gyakorlat',`<form data-form="exercise" data-id="${e.id||''}"><div class="form-grid">${input('name','Gyakorlat neve',e.name||'','text','required maxlength="160"')}${input('muscle','Izomcsoport',e.muscle||'','text','required maxlength="80"')}${input('equipment','Eszköz',e.equipment||'','text','required maxlength="100"')}<label>Kategória<select name="category">${Object.entries(categories).map(([k,v])=>`<option value="${k}" ${e.category===k?'selected':''}>${v}</option>`).join('')}</select></label></div>${check('active','Aktív gyakorlat',e.active!==0)}${formFooter()}</form>`);}
function workoutPage(){return head('Edzéslabor','A terv irányt ad. A napló a tényleges teljesítményt őrzi.',coach()&&writable()?button('new-plan','+ Edzésterv','',true):'')+`<section class="card"><div class="row"><div><div class="eyebrow">Tervezés</div><h2>Edzéstervek</h2></div><span class="badge">Terv ≠ tény</span></div>${plans.length?plans.map(p=>`<div class="list-row"><div><h3>${esc(p.name)}</h3><div class="muted">${p.exercises.length} gyakorlat · ${p.exercises.reduce((n,e)=>n+e.sets.length,0)} tervezett sorozat · ${dt(p.start_date)} ${p.phase?'· '+esc(p.phase):''}</div>${!p.active?'<span class="badge">Archivált</span>':''}</div><div class="actions">${button('view-plan','Megnyitás',`data-id="${p.id}"`)}${coach()&&writable()?button('copy-plan','Másolás',`data-id="${p.id}"`):''}${coach()&&writable()&&p.active?button('edit-plan','Szerkesztés',`data-id="${p.id}"`)+button('archive-plan','Archiválás',`data-id="${p.id}"`):''}</div></div>`).join(''):'<p class="muted">Még nincs hozzárendelt edzésterv.</p>'}</section>${factWriter()?`<section class="card section-gap"><div class="eyebrow">Mai munka</div><h2>Edzés vagy pihenőnap</h2><form data-form="start-workout"><div class="form-grid">${input('date','Dátum',today,'date',`required max="${today}" min="2000-01-01"`)}<label>Edzésterv<select name="plan_id" required><option value="">Válassz tervet</option>${plans.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label></div><div class="form-error" role="alert"></div><div class="row section-gap"><button type="submit" class="primary">Edzés megnyitása</button>${button('new-rest','Pihenőnap rögzítése')}</div></form></section>`:''}${activeWorkout?recordingPage(activeWorkout):''}<section class="card section-gap"><div class="row"><h2>Edzéstörténet</h2>${button('go-weekly','Heti elemzés')}</div>${workouts.length||rests.length?[...workouts.map(w=>({...w,type:'workout'})),...rests.map(r=>({...r,type:'rest'}))].sort((a,b)=>b.date.localeCompare(a.date)).map(w=>`<div class="list-row"><div><h3>${w.type==='rest'?'Pihenőnap':esc(w.name)}</h3><div class="muted">${dt(w.date)} · ${w.type==='rest'?'Explicit pihenő':w.status==='completed'?'Lezárt':w.status==='archived'?'Archivált':'Folyamatban'}</div></div><div class="actions">${w.type==='workout'?button('open-workout','Megnyitás',`data-id="${w.id}"`):factWriter()?button('remove-rest','Pihenőnap visszavonása',`data-id="${w.id}"`):''}</div></div>`).join(''):'<p class="muted">Még nincs rögzített edzés vagy pihenőnap.</p>'}</section>`;}
function planViewer(p){dialog(esc(p.name),`<p class="muted">Kezdés: ${dt(p.start_date)} · ${esc(p.phase||'Nincs ciklus')}</p>${p.note?`<p class="note">${esc(p.note)}</p>`:''}${p.exercises.map(e=>`<section class="plan-exercise"><h3>${esc(e.name)}</h3><div class="muted">${esc(e.muscle)} · ${categories[e.category]}</div><div class="table-wrap"><table><thead><tr><th>Sorozat</th><th>Terv kg</th><th>Terv ism.</th><th>RPE-cél</th><th>Típus</th></tr></thead><tbody>${e.sets.map(s=>`<tr><td>${s.number}</td><td>${num(s.planned_weight)}</td><td>${num(s.planned_reps)}</td><td>${num(s.planned_rpe)}</td><td>${s.warmup?'Bemelegítő':'Munka'}</td></tr>`).join('')}</tbody></table></div>${e.note?`<p class="help">${esc(e.note)}</p>`:''}</section>`).join('')}<div class="form-actions">${button('history','Módosítási előzmények',`data-entity="plan" data-id="${p.id}"`)}${button('close-dialog','Bezárás')}</div>`);}
function planBuilder(p=null){builder=p?structuredClone(p):{name:'',start_date:today,phase:'',note:'',exercises:[]};drawBuilder();}
function drawBuilder(){dialog(builder.id?'Edzésterv szerkesztése':'Új edzésterv',`<form data-form="plan"><div class="form-grid">${input('name','Terv neve',builder.name,'text','required maxlength="160"')}${input('start_date','Kezdődátum',builder.start_date,'date','required min="2000-01-01" max="2100-12-31"')}${input('phase','Ciklus · opcionális',builder.phase,'text','maxlength="120"')}${textarea('note','Tervjegyzet',builder.note,'maxlength="4000"')}</div><div class="separator"></div><div class="toolbar"><label class="full">Gyakorlat keresése / hozzáadása<input type="search" id="plan-exercise-search" placeholder="Szűrés név alapján…"><select id="plan-exercise-select" aria-label="Hozzáadandó gyakorlat"><option value="">Válassz gyakorlatot</option>${exercises.filter(e=>e.active&&!builder.exercises.some(b=>b.exercise_id===e.id)).map(e=>`<option value="${e.id}">${esc(e.name)} · ${esc(e.muscle)}</option>`).join('')}</select></label>${button('builder-add-exercise','+ Hozzáadás')}</div>${builder.exercises.map((e,ei)=>`<section class="plan-exercise" data-builder-exercise="${ei}"><div class="row"><div><h3>${esc(e.name)}</h3><span class="muted">${esc(e.muscle)} · ${categories[e.category]}</span></div><div class="exercise-controls">${button('builder-up','↑',`data-index="${ei}" aria-label="${esc(e.name)} feljebb" ${ei===0?'disabled':''}`)}${button('builder-down','↓',`data-index="${ei}" aria-label="${esc(e.name)} lejjebb" ${ei===builder.exercises.length-1?'disabled':''}`)}${button('builder-remove-exercise','Eltávolítás',`data-index="${ei}"`)}</div></div>${e.sets.map((s,si)=>`<div class="set-target" data-builder-set="${si}"><span class="muted">${si+1}.</span>${field('planned_weight','Terv kg',s.planned_weight,0,1000)}${input('planned_reps','Terv ism.',s.planned_reps??'','number','min="1" max="200" step="1" inputmode="numeric"')}${field('planned_rpe','RPE-cél',s.planned_rpe,6,10)}${check('warmup','Bemeleg.',s.warmup)}${button('builder-remove-set','×',`data-index="${ei}" data-set="${si}" aria-label="Sorozat eltávolítása"`)}</div>`).join('')}<div class="row section-gap">${button('builder-add-set','+ Sorozat',`data-index="${ei}"`)}</div>${textarea('exercise_note','Gyakorlatjegyzet',e.note||'','maxlength="2000"')}</section>`).join('')}<p class="help">A tervezett kg és ismétlés üresen is hagyható. A korábbi edzések külön pillanatfelvételt őriznek.</p>${formFooter('Edzésterv mentése')}</form>`);}
function captureBuilder(){const f=$('#dialog form');if(!f)return;for(const k of ['name','start_date','phase','note'])builder[k]=f.elements[k].value;f.querySelectorAll('[data-builder-exercise]').forEach(el=>{const e=builder.exercises[Number(el.dataset.builderExercise)];e.note=el.querySelector('[name="exercise_note"]').value;e.sets=[...el.querySelectorAll('[data-builder-set]')].map((s,i)=>({number:i+1,planned_weight:numeric(s.querySelector('[name="planned_weight"]').value),planned_reps:numeric(s.querySelector('[name="planned_reps"]').value),planned_rpe:numeric(s.querySelector('[name="planned_rpe"]').value),warmup:s.querySelector('[name="warmup"]').checked}));});}
function recordingPage(w){const writableSet=factWriter()&&w.status!=='archived';let groups=[];for(const s of w.sets){let g=groups.find(g=>g.position===s.position);if(!g){g={position:s.position,name:s.exercise_name,muscle:s.muscle,exercise_id:s.exercise_id,sets:[]};groups.push(g);}g.sets.push(s);}return `<section id="active-workout" class="section-gap"><div class="page-head"><div><div class="eyebrow">Tényleges teljesítmény</div><h2>${esc(w.name)}</h2><span class="muted">${dt(w.date)} · ${w.status==='completed'?'Lezárt':w.status==='archived'?'Archivált':'Folyamatban'} · ${num(w.duration_minutes)} perc</span></div>${button('hide-workout','Napló bezárása')}</div>${w.status==='completed'&&writableSet?'<div class="notice">Lezárt edzés. Utólagos javítás menthető; a módosítás az előzményekben megmarad.</div>':''}<div class="workout-layout"><div class="stack">${groups.map(g=>`<section class="card"><div class="eyebrow">${esc(g.muscle)}</div><h2>${esc(g.name)}</h2>${g.sets[0].exercise_note?`<p class="note">${esc(g.sets[0].exercise_note)}</p>`:''}${g.sets.map(s=>setCard(w,s,writableSet)).join('')}${writableSet?`<div class="section-gap">${button('add-workout-set','+ Tényleges sorozat',`data-id="${g.exercise_id}"`)}</div>`:''}</section>`).join('')}</div><aside class="workout-aside">${metric('Keménysorozat',num(w.stats.hardSets),'')}${metric('Súlyzós volumen',num(w.stats.volume),'kg')}${metric('Átlagos RPE',num(w.stats.averageRpe),'')}<section class="card"><p class="help">Saját testsúly: ${w.stats.bodyweightSets} munkasorozat. Kardió: ${num(w.stats.cardioMinutes)} perc. A kettő nem része a súlyzós volumennek.</p>${w.note?`<p class="note">${esc(w.note)}</p>`:''}${writableSet?button('add-workout-exercise','+ Gyakorlat','class="full"')+button('workout-meta','Jegyzet és időpontok','class="full"')+`<div class="section-gap">${button('toggle-workout',w.status==='completed'?'Edzés újranyitása':'Edzés lezárása','class="full"',true)}</div><div class="section-gap">${button('archive-workout','Edzés archiválása','class="full danger"')}</div>`:''}<div class="section-gap">${button('history','Edzéselőzmények',`data-entity="workout" data-id="${w.id}" class="full"`)}</div></section></aside></div></section>`;}
function setCard(w,s,canWrite){const cardio=s.category==='cardio',ref=s.previous;const previous=ref?(cardio?`${num(ref.duration_minutes)} perc · ${num(ref.distance_km)} km`:`${num(ref.actual_weight)} kg × ${num(ref.actual_reps)}`)+' · '+dt(ref.date):'Még nincs korábbi eredmény';
  const fields=`<div class="numbers">${cardio?field('duration_minutes','Tényleges idő (perc)',s.duration_minutes,0.1,1440,true)+field('distance_km','Távolság (km)',s.distance_km,0,1000):field('actual_weight',s.category==='bodyweight'?'Hozzáadott súly (kg) · 0 is érvényes':'Tényleges súly (kg)',s.actual_weight,0,1000,true)+input('actual_reps','Tényleges ismétlés',s.actual_reps??'','number','min="1" max="200" step="1" required inputmode="numeric"')}</div><details><summary>RPE, pihenő és sorozatjegyzet</summary><div class="form-grid">${field('rpe','RPE · 6–10',s.rpe,6,10)}${field('rest_minutes','Pihenő (perc) · opcionális',s.rest_minutes,0,120)}</div>${check('warmup','Bemelegítő sorozat',!!s.warmup)}${textarea('note','Sorozatjegyzet',s.note,'maxlength="2000"')}</details>`;
  return `<div class="set-card ${s.completed?'completed':''}" id="set-${s.id}"><div class="record-header"><span class="set-number">${s.number}. SOROZAT ${s.warmup?'· BEMELEGÍTŐ':''}</span>${s.completed?`<span class="badge good">${s._pending?'Helyben mentve · függő':'Mentve'}</span>`:'<span class="badge burgundy">Még nincs tényadat</span>'}</div><div class="reference"><div>Előző alkalom<strong>${previous}</strong></div><div>Terv<strong>${cardio?'Kardió':num(s.planned_weight)+' kg × '+num(s.planned_reps)}${s.planned_rpe!=null?' · RPE '+num(s.planned_rpe):''}</strong></div></div>${canWrite?`${s.completed?`<details><summary><strong>${cardio?num(s.duration_minutes)+' perc':num(s.actual_weight)+' kg × '+num(s.actual_reps)}</strong> &nbsp; · Módosítás</summary>`:''}<form data-form="set" data-id="${s.id}">${fields}<div class="form-error" role="alert"></div><button type="submit" class="primary save-set">${s.completed?'MÓDOSÍTÁS MENTÉSE':'SOROZAT KÉSZ'}</button>${s.completed?`<div class="form-actions">${button('unset','Teljesítés visszavonása',`data-id="${s.id}"`)}${button('history','Előzmények',`data-entity="set" data-id="${s.id}"`)}</div>`:''}</form>${s.completed?'</details>':''}`:`<p class="section-gap">${s.completed?(cardio?num(s.duration_minutes)+' perc · '+num(s.distance_km)+' km':num(s.actual_weight)+' kg × '+num(s.actual_reps)):'Nincs tényleges teljesítés'}${s.rpe!=null?' · RPE '+num(s.rpe):''}</p>${s.note?`<p class="help">${esc(s.note)}</p>`:''}${button('history','Előzmények',`data-entity="set" data-id="${s.id}"`)}`}</div>`;
}
function lineChart(points,label,unit=''){const actual=points.filter(p=>p.value!=null);if(!actual.length)return '<div class="chart-empty">Még nincs rögzített adat ehhez a grafikonhoz.</div>';const width=560,height=200,left=48,right=20,top=15,bottom=38,min=Math.min(0,...actual.map(p=>p.value)),max=Math.max(1,...actual.map(p=>p.value)),x=i=>left+(width-left-right)*(actual.length===1?.5:i/(actual.length-1)),y=v=>height-bottom-(v-min)/(max-min)*(height-top-bottom),coords=actual.map((p,i)=>`${x(i)},${y(p.value)}`).join(' ');return `<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(label)}"><line class="axis" x1="${left}" y1="${height-bottom}" x2="${width-right}" y2="${height-bottom}"/><text x="0" y="20">${num(max)}</text><text x="0" y="${height-bottom}">${num(min)}</text><polyline class="line" points="${coords}"/>${actual.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.value)}" r="4"><title>${dt(p.date)}: ${num(p.value)} ${unit}</title></circle>`).join('')}<text x="${left}" y="${height-10}">${dt(actual[0].date)}</text><text text-anchor="end" x="${width-right}" y="${height-10}">${dt(actual.at(-1).date)}</text></svg><details class="chart-table"><summary class="muted">Pontos értékek</summary><table><thead><tr><th>Dátum</th><th>${label}</th></tr></thead><tbody>${actual.map(p=>`<tr><td>${dt(p.date)}</td><td>${num(p.value)} ${unit}</td></tr>`).join('')}</tbody></table></details>`;}
function muscleChart(values){const entries=Object.entries(values);if(!entries.length)return '<div class="chart-empty">Ezen a héten még nincs keménysorozat.</div>';const max=Math.max(...entries.map(x=>x[1]));return `<div class="muscle-bars" role="img" aria-label="Heti keménysorozatok izomcsoportonként">${entries.map(([name,value])=>`<div class="muscle-row"><span>${esc(name)}</span><meter min="0" max="${max}" value="${value}" aria-label="${esc(name)}: ${value} keménysorozat">${value}</meter><strong>${value}</strong></div>`).join('')}</div>`;}
async function weeklyPage(week){const stats=await api.request(endpoint('statistics')+`?from=${week}&to=${shift(week,6)}`),all=await api.request(endpoint('statistics')+`?from=${client.start_date}&to=${today}`);return head('A hét mérlege','Valós sorozatokból számolt teljesítmény, hétfőtől vasárnapig.')+`<div class="toolbar">${button('prev-week','← Előző hét',`data-week="${week}"`)}<span class="muted">${dt(week)} – ${dt(shift(week,6))}</span>${button('next-week','Következő hét →',`data-week="${week}" ${week>=monday(today)?'disabled':''}`)}</div><div class="metrics">${metric('Lezárt edzések',stats.completedWorkouts,'')}${metric('Keménysorozat',stats.hardSets,'')}${metric('Súlyzós volumen',num(stats.volume),'kg')}${metric('Átlagos RPE',num(stats.averageRpe),'')}</div><div class="grid"><section class="card"><div class="eyebrow">Heti megoszlás</div><h2>Sorozatok izomcsoportonként</h2>${muscleChart(stats.muscle)}</section><section class="card"><div class="eyebrow">Edzéstörténet</div><h2>Volumen alakulása</h2>${lineChart(all.series.map(s=>({date:s.date,value:s.volume})),'Volumen','kg')}</section><section class="card"><div class="eyebrow">Terhelésérzet</div><h2>Átlagos RPE</h2>${lineChart(all.series.map(s=>({date:s.date,value:s.rpe})),'RPE')}</section><section class="card"><div class="eyebrow">Gyakorlatonként</div><h2>Teljesítményváltozás</h2>${Object.keys(all.performance).length?`<label>Gyakorlat<select id="performance-select">${Object.entries(all.performance).map(([id,p])=>`<option value="${id}">${esc(p.name)}</option>`).join('')}</select></label><div id="performance-chart"></div>`:'<div class="chart-empty">Még nincs tényleges sorozat.</div>'}</section></div><p class="help section-gap">A súlyzós volumen minden teljesített súlyzós sorozat tényleges kg × ismétlés értéke, a bemelegítéssel együtt. Keménysorozat: nem bemelegítő, két tényleges mezővel. Saját testsúly és kardió külön: ${stats.bodyweightSets} sorozat / ${num(stats.cardioMinutes)} perc.</p><div id="performance-data" hidden>${esc(JSON.stringify(all.performance))}</div>`;}
function performanceChart(){const el=$('#performance-data'),select=$('#performance-select');if(!el||!select)return;const p=JSON.parse(el.textContent)[select.value];const cardio=p.category==='cardio';$('#performance-chart').innerHTML=lineChart(p.points.map(s=>({date:s.date,value:cardio?s.duration:s.weight})),cardio?'Kardió idő':'Tényleges súly',cardio?'perc':'kg')+`<p class="help">${cardio?'Rögzített idő sorozatonként.':p.category==='bodyweight'?'Rögzített hozzáadott súly, nem a testtömeg.':'Rögzített súly sorozatonként; az ismétlésszám az alábbi táblázatban.'}</p><div class="chart-table"><table><thead><tr><th>Dátum</th><th>${cardio?'Perc':'Kg'}</th><th>${cardio?'Km':'Ismétlés'}</th><th>RPE</th></tr></thead><tbody>${p.points.map(s=>`<tr><td>${dt(s.date)}</td><td>${num(cardio?s.duration:s.weight)}</td><td>${num(cardio?s.distance:s.reps)}</td><td>${num(s.rpe)}</td></tr>`).join('')}</tbody></table></div>`;}
function measurementsPage(){return head('Mérések','A testsúly változását a méréseidből számoljuk. Az új mérés hozzáadódik az előzményekhez.',factWriter()?button('new-measurement','+ Mérés rögzítése','',true):'')+`<div class="grid"><section class="card"><h2>Testsúly alakulása</h2>${lineChart([...measurementRows].reverse().map(m=>({date:m.date,value:m.weight})),'Testsúly','kg')}</section><section class="card"><h2>Mérési előzmények</h2>${measurementRows.length?`<div class="table-wrap"><table><thead><tr><th>Dátum</th><th>Testsúly</th><th>Derék</th><th>Mellkas</th><th>Csípő</th></tr></thead><tbody>${measurementRows.map(m=>`<tr><td>${dt(m.date)}</td><td>${num(m.weight)} kg</td><td>${num(m.data.waist)}</td><td>${num(m.data.chest)}</td><td>${num(m.data.hip)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">Még nincs mérés. A kezdősúly nem helyettesíti az aktuális mérést.</p>'}</section></div>`;}
function foodPage(){return head('Kajanapló','A ténylegesen elfogyasztott étkezések. A hiányzó tápértékeket nem becsüljük.',factWriter()?button('new-food','+ Étkezés','',true):'')+`<section class="card">${foodRows.length?foodRows.map(f=>`<div class="list-row"><div><h3>${esc(f.name)} <span class="muted">${num(f.grams)} g</span></h3><div class="muted">${dt(f.date)} · ${f.meal}. étkezés</div><div class="help">Fehérje ${num(f.protein)} g · Szénhidrát ${num(f.carbs)} g · Zsír ${num(f.fat)} g · ${num(f.calories)} kcal</div></div>${factWriter()?button('archive-food','Bejegyzés visszavonása',`data-id="${f.id}"`):''}</div>`).join(''):empty('Még nincs étkezés','A teljesített napokhoz kajanapló-bejegyzés is szükséges. A napot nem jelöljük automatikusan teljesnek.',factWriter()?'new-food':'','Étkezés rögzítése')}</section>`;}
function dailyPage(){const week=monday(today),names=['H','K','Sze','Cs','P','Szo','V'];return head('Napi napló','A napi állapot, étkezés és edzés egyetlen áttekintésben.',factWriter()?button('new-daily','Napi állapot rögzítése','',true):'')+`<section class="card"><h2>Aktuális hét</h2><div class="week">${names.map((n,i)=>{const date=shift(week,i),food=foodRows.some(f=>f.date===date),w=workouts.some(w=>w.date===date&&w.status!=='archived'&&w.completed_sets>0),rest=rests.some(r=>r.date===date);return `<div class="week-day ${food&&(rest||w)?'full':''}"><strong>${n}</strong><div class="muted">${date.slice(8)}</div><div class="status">${rest?'Pihenő':w?'Edzés':'—'}</div><div class="status">${food?'Étkezés ✓':'Étkezés —'}</div></div>`;}).join('')}</div><p class="help section-gap">Az edzés megnyitása önmagában még nem teljesítés: legalább egy tényleges sorozatot rögzíteni kell. A pontos teljesített napokat az adatlap mutatja.</p>${factWriter()?button('new-rest','Pihenőnap rögzítése'):''}</section><section class="card section-gap"><h2>Állapotnapló</h2>${dailyRows.length?dailyRows.map(d=>`<div class="list-row"><div><h3>${dt(d.date)}</h3><div class="muted">Alvás: ${num(d.data.sleep)} óra · Energia: ${num(d.data.energy)} / 5 · ${d.closed_at?'Nap lezárva':'Nyitott nap'}</div>${d.data.note?`<p class="note">${esc(d.data.note)}</p>`:''}${d.data.pain?`<p class="help">Fájdalom: ${esc(d.data.pain)}</p>`:''}${d.data.lab_date?`<p class="help">Vérkép dátuma: ${dt(d.data.lab_date)}</p>`:''}</div>${factWriter()?button('edit-daily','Szerkesztés',`data-id="${d.id}"`):''}</div>`).join(''):'<p class="muted">Még nincs rögzített napi állapot.</p>'}</section>`;}
function recordsPage(kind){const can=kind==='photo'?factWriter():coach()&&writable(),titles={diet:'Étrend',medication:'Gyógyszer',photo:'Fotónapló'},texts={diet:'Edzői étrendi útmutatás, elkülönítve a tényleges kajanaplótól.',medication:'Állandó dózislista és megőrzött változások. Nincs dózisjavaslat vagy bevételjelölés.',photo:'Privát fejlődési képek, a kliens és a hozzárendelt edző számára.'};return head(titles[kind],texts[kind],can?button('new-record','+ '+(kind==='photo'?'Fotó':'Bejegyzés'),`data-kind="${kind}"`,true):'')+`<section class="card ${kind==='photo'?'photo-grid':''}">${records.length?records.map(r=>`<article class="${kind==='photo'?'':'list-row'}"><div>${kind==='photo'?`<img src="data:${esc(r.data.type)};base64,${r.data.base64}" alt="Fejlődési fotó ${dt(r.data.date)}"><h3>${dt(r.data.date)}</h3>`:`<h3>${esc(r.data.name)}</h3><p class="muted">${kind==='diet'?r.data.meals+' étkezés':esc(r.data.dose)}</p>`}${r.data.note?`<p class="note">${esc(r.data.note)}</p>`:''}<div class="help">Rögzítve: ${dt(r.created_at)}</div></div>${can?`<div class="actions">${kind!=='photo'?button('edit-record','Szerkesztés',`data-id="${r.id}" data-kind="${kind}"`):''}${button('archive-record','Archiválás',`data-id="${r.id}" data-kind="${kind}"`)}${kind!=='photo'?button('history','Változások',`data-entity="${kind}" data-id="${r.id}"`):''}</div>`:''}</article>`).join(''):`<p class="muted">Még nincs bejegyzés.</p>`}</section>${kind==='diet'?'<p class="help section-gap">Jelenleg szöveges étrend és 5/6 étkezés kezelhető. A részletes ételkatalógus, grammonkénti számítás és PDF-export következő fejlesztés.</p>':''}`;}
function settingsPage(){return head('Beállítások','Munkaterület, adatbiztonság és az alkalmazás állapota.')+`<div class="grid"><section class="card"><h2>Fiók és munkaterület</h2><div class="settings-line"><h3>IMPAVIDUS LAB</h3><p class="muted">${esc(user.username)} · ${coach()?'Edzői':'Kliens'} fiók</p></div><div class="settings-line"><h3>Mentési állapot</h3><p class="muted">A sikeres mentések a szerver SQLite-adatbázisában tárolódnak. A helyi függő mentéseket a felső állapotsáv jelzi.</p></div>${button('logout','Kijelentkezés')}${coach()&&client&&writable()?button('preferences','Opcionális egészségmezők'):''}${client?button('export','Kliensadatok exportálása'):''}</section><section class="card"><h2>Telepítés és biztonsági mentés</h2><p class="muted">A PWA böngészőből telepíthető támogatott környezetben. A szolgáltatásmunkás csak az alkalmazás felületét gyorsítótárazza; személyes API-adatokat nem.</p><p class="muted">A biztonsági mentés szerveroldali parancs: <code>npm run backup</code>. A mentést külön, titkosított tárhelyen őrizd. Az automatikus mentések beállításait az .env fájl tartalmazza.</p><p class="help">A szerver alapból kizárólag ezen a gépen, a 127.0.0.1 címen érhető el. Valódi telefonos hozzáféréshez HTTPS-es kiszolgálás szükséges.</p></section></div>`;}
function numeric(x){return x===''||x==null?null:Number(x);}
function values(f,numbers=[],booleans=[]){const o=Object.fromEntries(new FormData(f));for(const k of numbers)o[k]=numeric(o[k]);for(const k of booleans)o[k]=!!f.elements[k]?.checked;return o;}
async function imageFile(file){if(!file||!['image/jpeg','image/png'].includes(file.type)||file.size>10*1024*1024)throw new Error('Legfeljebb 10 MB-os PNG vagy JPEG képet válassz.');const bitmap=await createImageBitmap(file),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return canvas.toDataURL('image/jpeg',.8).split(',')[1];}
function simpleForm(title,kind,html,data=''){dialog(title,`<form data-form="${kind}" ${data}>${html}${formFooter()}</form>`);}
function dailyForm(d=null){const n=d?.data||{};simpleForm('Napi állapot','daily',`<div class="form-grid">${input('date','Dátum',d?.date||today,'date',`required max="${today}" min="2000-01-01" ${d?'readonly':''}`)}${field('sleep','Alvás (óra)',n.sleep,0,24)}${input('energy','Energia · 1–5',n.energy??'','number','min="1" max="5" step="1"')}${client.preferences.labs?input('lab_date','Vérkép dátuma · opcionális',n.lab_date||'','date','min="2000-01-01" max="2100-12-31"'):''}${client.preferences.blood_pressure?input('blood_pressure','Vérnyomás · opcionális',n.blood_pressure||'','text','maxlength="30"'):''}${client.preferences.blood_glucose?field('blood_glucose','Vércukor · opcionális',n.blood_glucose,0.1,50):''}<div class="span">${textarea('pain','Fájdalom / panasz',n.pain||'','maxlength="2000"')}${textarea('note','Napi megjegyzés',n.note||'','maxlength="4000"')}${check('closed','Nap lezárása (a mai hiányzó nap csak ekkor számít)',!!d?.closed_at)}</div></div>`,`data-id="${d?.id||''}"`);}
function recordForm(kind,r=null){const d=r?.data||{};const html=kind==='photo'?`${input('date','Dátum',d.date||today,'date',`required max="${today}" min="2000-01-01"`)}<label>Fotó<input type="file" name="image" accept="image/jpeg,image/png" required></label>`:`<div class="form-grid">${input('name',kind==='diet'?'Étrend neve':'Gyógyszer neve',d.name||'','text','required maxlength="160"')}${kind==='diet'?`<label>Étkezések száma<select name="meals"><option value="5" ${d.meals===5?'selected':''}>5</option><option value="6" ${d.meals===6?'selected':''}>6</option></select></label>`:input('dose','Dózis szövegesen',d.dose||'','text','required maxlength="160"')}</div>`;simpleForm(kind==='photo'?'Fejlődési fotó':kind==='diet'?'Étrendi útmutatás':'Dózislista','record',html+textarea('note','Megjegyzés',d.note||'',`maxlength="${kind==='diet'?10000:2000}"`),`data-kind="${kind}" data-id="${r?.id||''}"`);}
const modules=createModules({api,$,esc,num,dt,input,field,textarea,check,button,metric,head,lineChart,muscleChart,simpleForm,dialog,values,toast,refresh,shift,monday,formFooter,state:()=>({user,client,clients,today,page})});
document.addEventListener('submit',async event=>{
  const f=event.target;if(!f.dataset.form)return;event.preventDefault();const submit=f.querySelector('[type="submit"]'),err=f.querySelector('.form-error');err.textContent='';submit.disabled=true;
  try {
    const kind=f.dataset.form,id=f.dataset.id;
    if(await modules.submit(kind,f)){$('#dialog').close();await refresh();toast(api.lastPending?'Helyben mentve · szinkronra vár.':'Mentve az adatbázisba.');return;}
    if(kind==='auth'){const result=await api.request('/auth/'+f.dataset.mode,'POST',values(f));api.csrf=result.csrf;location.hash='/'+(result.role==='client'?'profile':'clients');await refresh();return;}
    if(kind==='client'){const n=values(f,['starting_weight','height','target_weight']);if(id)n.version=client.version;const c=await api.request(id?endpoint(): '/clients',id?'PATCH':'POST',n);$('#dialog').close();route('profile',c.id);toast('Kliensprofil mentve.');return;}
    if(kind==='account-access')await api.request(endpoint('access'),'POST',{...values(f),version:Number(f.dataset.version)});
    if(kind==='exercise'){const n=values(f,[],['active']),old=exercises.find(e=>e.id===id);if(old)n.version=old.version;await api.request('/exercises'+(id?'/'+id:''),id?'PATCH':'POST',n);}
    if(kind==='plan'){captureBuilder();const data={...builder};await api.request(endpoint('plans'+(builder.id?'/'+builder.id:'')),builder.id?'PATCH':'POST',data);builder=null;}
    if(kind==='start-workout'){activeWorkout=await api.request(endpoint('workouts'),'POST',values(f));await refresh();$('#active-workout')?.scrollIntoView({behavior:'smooth',block:'start'});toast('Edzés megnyitva. A ténymezők üresek.');return;}
    if(kind==='set'){const s=activeWorkout.sets.find(s=>s.id===id),n=values(f,['actual_weight','actual_reps','rpe','rest_minutes','duration_minutes','distance_km'],['warmup']);n.completed=true;n.version=s.version;activeWorkout=await api.saveSet(client.id,activeWorkout.id,id,n);await refresh();toast(api.lastPending?'Sorozat helyben mentve · szinkronra vár.':'Sorozat mentve az adatbázisba.');const next=activeWorkout.sets.find(s=>!s.completed);if(next){const el=$('#set-'+next.id);el?.scrollIntoView({behavior:'smooth',block:'center'});el?.querySelector('input')?.focus({preventScroll:true});}return;}
    if(kind==='workout-meta'){const n=values(f);n.version=activeWorkout.version;for(const k of ['started_at','ended_at'])n[k]=n[k]?new Date(n[k]).toISOString():null;activeWorkout=await api.request(endpoint('workouts/'+activeWorkout.id),'PATCH',n);}
    if(kind==='rest')await api.request(endpoint('rest-days'),'POST',values(f));
    if(kind==='note')await api.request(endpoint('notes'),'POST',values(f));
    if(kind==='measurement')await api.request(endpoint('measurements'),'POST',values(f,['weight','waist','chest','hip','arm','thigh']));
    if(kind==='food')await api.request(endpoint('food-logs'),'POST',values(f,['meal','grams','protein','carbs','fat','calories']));
    if(kind==='daily'){const n=values(f,['sleep','energy','blood_glucose'],['closed']);const old=dailyRows.find(d=>d.id===id);if(old){n.version=old.version;for(const k of ['blood_pressure','blood_glucose','lab_date'])if(!f.elements[k])n[k]=old.data[k];}await api.request(endpoint('daily-logs'),'POST',n);}
    if(kind==='avatar'){const base64=await imageFile(f.elements.image.files[0]);await api.request(endpoint('avatar'),'POST',{base64,version:client.version});}
    if(kind==='record'){const data=values(f,['meals']);delete data.image;if(f.dataset.kind==='photo')data.base64=await imageFile(f.elements.image.files[0]);const old=records.find(r=>r.id===id);await api.request(endpoint('records'+(id?'/'+id:'')),id?'PATCH':'POST',{kind:f.dataset.kind,data,version:old?.version});}
    if(kind==='copy'){const p=plans.find(p=>p.id===id);await api.request(endpoint('plans/'+p.id+'/copy'),'POST',values(f));}
    if(kind==='add-workout-exercise'){activeWorkout=await api.request(endpoint('workouts/'+activeWorkout.id+'/sets'),'POST',{...values(f),version:activeWorkout.version});}
    if(kind==='preferences')await api.request(endpoint('preferences'),'PATCH',{...values(f,[],['blood_pressure','blood_glucose','labs']),version:client.version});
    if(kind==='import'){let items;try{items=JSON.parse(f.elements.json.value);}catch{throw new Error('Hibás JSON-fájl.');}const result=await api.request('/exercises/import','POST',{items});toast(`${result.inserted.length} új gyakorlat, ${result.skipped.length} korábban már szerepelt.`);}
    $('#dialog').close();await refresh();toast(api.lastPending?'Helyben mentve · szinkronra vár.':'Mentve az adatbázisba.');
  }catch(e){err.textContent=e.message;toast(e.message,true);}finally{submit.disabled=false;}
});
document.addEventListener('click',async event=>{
  if(event.target.closest('.nav a')){$('.shell')?.classList.remove('menu-open');$('[data-action="menu"]')?.setAttribute('aria-expanded','false');}
  const b=event.target.closest('[data-action]');if(!b)return;const action=b.dataset.action,id=b.dataset.id;try{
    if(await modules.action(action,b))return;
    if(action==='close-dialog'){$('#dialog').close();return;}
    if(action==='retry'){await refresh();return;}
    if(action==='menu'){const shell=$('.shell'),open=shell.classList.toggle('menu-open');b.setAttribute('aria-expanded',String(open));return;}
    if(action==='logout'){await api.request('/auth/logout','POST',{});activeWorkout=null;client=null;$('#dialog').close();await refresh();return;}
    if(action==='open-client'){activeWorkout=null;route('profile',id);return;}
    if(action==='new-client'){profileForm();return;}
    if(action==='edit-client'){profileForm(client);return;}
    if(action==='archive-client'){dialog('Kliens archiválása',`<p>${esc(client.name)} összes adata megmarad. A kliens belépése letiltásra kerül.</p><div class="form-actions">${button('close-dialog','Mégse')}${button('confirm-archive-client','Archiválás','',true)}</div>`);return;}
    if(action==='confirm-archive-client'){await api.request(endpoint(),'DELETE',{version:client.version});$('#dialog').close();route('clients');return;}
    if(action==='restore-client'){await api.request(endpoint('restore'),'POST',{});await refresh();toast('Kliens visszaállítva.');return;}
    if(action==='avatar'){simpleForm('Profilkép feltöltése','avatar','<label>JPEG vagy PNG kép<input type="file" name="image" accept="image/jpeg,image/png" required></label><p class="help">A böngésző legfeljebb 1200 pixelre méretezi és JPEG-ként küldi. A szerver ellenőrzi a formátumot és a méretet.</p>'+ (client.has_avatar?button('remove-avatar','Jelenlegi kép eltávolítása'):''));return;}
    if(action==='remove-avatar'){await api.request(endpoint('avatar'),'DELETE',{version:client.version});$('#dialog').close();await refresh();return;}
    if(action==='account-access'){const account=await api.request(endpoint('access'));simpleForm('Kliens belépési adatai','account-access',input('username','Felhasználónév',account.username,'text','required minlength="3" maxlength="254" autocomplete="off" autocapitalize="none" spellcheck="false"')+input('password',account.has_password?'Új jelszó (opcionális)':'Jelszó','','password',`minlength="12" maxlength="128" autocomplete="new-password" ${account.has_password?'':'required'}`)+'<p class="help">Legalább 12 karakteres jelszó. Meglévő fióknál az üres jelszómező megtartja a jelenlegi jelszót. Mentés után a kliensnek újra be kell lépnie.</p>',`data-version="${account.version}"`);return;}
    if(action==='new-note'){simpleForm('Fejlődési megjegyzés','note',textarea('text','Megjegyzés','','required maxlength="4000"'));return;}
    if(action==='archive-note'){await api.request(endpoint('notes/'+id),'DELETE',{});await refresh();return;}
    if(action==='go-workouts'||action==='go-weekly'){route(action==='go-workouts'?'workouts':'weekly');return;}
    if(action==='new-exercise'){exerciseForm();return;}
    if(action==='edit-exercise'){exerciseForm(exercises.find(e=>e.id===id));return;}
    if(action==='toggle-exercise'){const e=exercises.find(e=>e.id===id);await api.request('/exercises/'+id,'PATCH',{...e,active:!e.active});await refresh();return;}
    if(action==='import-exercises'){simpleForm('Licencelt gyakorlatimport','import',`<p class="help">Ellenőrzött JSON tömb: name, muscle, equipment, category, source, source_id, license (CC0-1.0 vagy CC-BY-4.0), author, source_url. A licencadatok helyességét import előtt ellenőrizni kell. A forrásazonosítók és az azonos gyakorlatok duplikációját a szerver kiszűri.</p>${textarea('json','JSON tömb','','required')}`);return;}
    if(action==='new-plan'){planBuilder();return;}
    if(action==='edit-plan'){planBuilder(plans.find(p=>p.id===id));return;}
    if(action==='view-plan'){planViewer(plans.find(p=>p.id===id));return;}
    if(action==='copy-plan'){const p=plans.find(p=>p.id===id);simpleForm('Edzésterv másolása','copy',input('name','Új terv neve',p.name+' — másolat','text','required maxlength="160"')+`<label>Célkliens<select name="client_id">${clients.filter(c=>!c.archived_at).map(c=>`<option value="${c.id}" ${c.id===client.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label>`,`data-id="${id}"`);return;}
    if(action==='archive-plan'){const p=plans.find(p=>p.id===id);await api.request(endpoint('plans/'+id),'DELETE',{version:p.version});await refresh();return;}
    if(action.startsWith('builder-')){captureBuilder();const i=Number(b.dataset.index),si=Number(b.dataset.set);if(action==='builder-add-exercise'){const e=exercises.find(e=>e.id===$('#plan-exercise-select').value);if(!e)throw new Error('Válassz gyakorlatot.');builder.exercises.push({exercise_id:e.id,name:e.name,muscle:e.muscle,equipment:e.equipment,category:e.category,note:'',sets:[{planned_reps:null,planned_weight:null,planned_rpe:null,warmup:false}]});}if(action==='builder-remove-exercise')builder.exercises.splice(i,1);if(action==='builder-up'&&i>0)[builder.exercises[i-1],builder.exercises[i]]=[builder.exercises[i],builder.exercises[i-1]];if(action==='builder-down'&&i<builder.exercises.length-1)[builder.exercises[i+1],builder.exercises[i]]=[builder.exercises[i],builder.exercises[i+1]];if(action==='builder-add-set')builder.exercises[i].sets.push({planned_reps:null,planned_weight:null,planned_rpe:null,warmup:false});if(action==='builder-remove-set')builder.exercises[i].sets.splice(si,1);drawBuilder();return;}
    if(action==='open-workout'){activeWorkout=await api.request(endpoint('workouts/'+id));await refresh();$('#active-workout')?.scrollIntoView({behavior:'smooth',block:'start'});return;}
    if(action==='hide-workout'){activeWorkout=null;await refresh();return;}
    if(action==='toggle-workout'){activeWorkout=await api.request(endpoint('workouts/'+activeWorkout.id),'PATCH',{version:activeWorkout.version,status:activeWorkout.status==='completed'?'in_progress':'completed'});await refresh();toast(activeWorkout.status==='completed'?'Edzés lezárva.':'Edzés újranyitva.');return;}
    if(action==='archive-workout'){dialog('Edzés archiválása','<p>Az edzés és a sorozatok megmaradnak az előzményekben. A nap ezután pihenőnapként is rögzíthető.</p><div class="form-actions">'+button('close-dialog','Mégse')+button('confirm-archive-workout','Archiválás','',true)+'</div>');return;}
    if(action==='confirm-archive-workout'){await api.request(endpoint('workouts/'+activeWorkout.id),'DELETE',{version:activeWorkout.version});activeWorkout=null;$('#dialog').close();await refresh();return;}
    if(action==='unset'){const s=activeWorkout.sets.find(s=>s.id===id);activeWorkout=await api.saveSet(client.id,activeWorkout.id,id,{version:s.version,completed:false,actual_weight:null,actual_reps:null,rpe:null,warmup:!!s.warmup,note:s.note});await refresh();return;}
    if(action==='add-workout-set'){activeWorkout=await api.request(endpoint('workouts/'+activeWorkout.id+'/sets'),'POST',{version:activeWorkout.version,exercise_id:id});await refresh();toast('Új, üres ténysorozat hozzáadva.');return;}
    if(action==='add-workout-exercise'){simpleForm('Tényleges gyakorlat hozzáadása','add-workout-exercise',`<label>Gyakorlat<select name="exercise_id" required><option value="">Válassz gyakorlatot</option>${exercises.filter(e=>e.active&&!activeWorkout.sets.some(s=>s.exercise_id===e.id)).map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}</select></label><p class="help">A naplóhoz ad új gyakorlatot, az edzéstervet nem módosítja.</p>`);return;}
    if(action==='preferences'){simpleForm('Opcionális egészségmezők','preferences',check('blood_pressure','Vérnyomás megjelenítése',client.preferences.blood_pressure)+check('blood_glucose','Vércukor megjelenítése',client.preferences.blood_glucose)+check('labs','Vérkép dátumának megjelenítése',client.preferences.labs)+'<p class="help">Alapértelmezetten kikapcsolva. A vérképnél csak dátumot tárolunk.</p>');return;}
    if(action==='workout-meta'){const local=x=>x?new Date(new Date(x).getTime()-new Date(x).getTimezoneOffset()*60000).toISOString().slice(0,16):'';simpleForm('Edzésjegyzet és időpontok','workout-meta',`<div class="form-grid">${input('name','Edzés neve',activeWorkout.name,'text','required maxlength="160"')}${input('started_at','Kezdési idő',local(activeWorkout.started_at),'datetime-local')}${input('ended_at','Befejezési idő',local(activeWorkout.ended_at),'datetime-local')}</div>${textarea('note','Edzésjegyzet',activeWorkout.note,'maxlength="4000"')}<p class="help">A befejezési idő lezárt edzésnél tárolható. Hiányzó időpontból nem számolunk időtartamot.</p>`);return;}
    if(action==='new-rest'){simpleForm('Pihenőnap','rest',input('date','Dátum',today,'date',`required max="${today}" min="2000-01-01"`)+textarea('note','Megjegyzés','','maxlength="2000"')+'<p class="help">Ha a napon már van aktív edzés, azt előbb archiválni kell.</p>');return;}
    if(action==='remove-rest'){await api.request(endpoint('rest-days/'+id),'DELETE',{});await refresh();return;}
    if(action==='history'){const rows=await api.request(endpoint('history')+`?entity=${b.dataset.entity}&id=${id}`);dialog('Módosítási előzmények',rows.length?rows.map(r=>`<div class="revision"><strong>${new Date(r.created_at).toLocaleString('hu-HU')}</strong><details><summary class="muted">Mentett változás</summary><pre>${esc(JSON.stringify({előtte:r.before,utána:r.after},null,2))}</pre></details></div>`).join(''):'<p class="muted">Még nincs módosítás.</p>');return;}
    if(action==='prev-week'||action==='next-week'){location.hash=`/weekly?client=${client.id}&week=${shift(b.dataset.week,action==='prev-week'?-7:7)}`;return;}
    if(action==='new-measurement'){simpleForm('Mérés rögzítése','measurement',`<div class="form-grid">${input('date','Dátum',today,'date',`required max="${today}" min="2000-01-01"`)}${field('weight','Testsúly (kg)',null,20,500,true)}${field('waist','Derék (cm)',null,1,300)}${field('chest','Mellkas (cm)',null,1,300)}${field('hip','Csípő (cm)',null,1,300)}${field('arm','Kar (cm)',null,1,300)}${field('thigh','Comb (cm)',null,1,300)}</div><p class="help">A testsúly kötelező, a kerületek opcionálisak. A mérési előzmény megmarad.</p>`);return;}
    if(action==='new-food'){simpleForm('Tényleges étkezés','food',`<div class="form-grid">${input('date','Dátum',today,'date',`required max="${today}" min="2000-01-01"`)}${input('meal','Étkezés száma','1','number','required min="1" max="6" step="1"')}${input('name','Étel megnevezése','','text','required maxlength="160"')}${field('grams','Elfogyasztott mennyiség (g)',null,0.1,10000,true)}${field('protein','Fehérje összesen (g)',null,0,10000)}${field('carbs','Szénhidrát összesen (g)',null,0,10000)}${field('fat','Zsír összesen (g)',null,0,10000)}${field('calories','Energia összesen (kcal)',null,0,10000)}</div><p class="help">A tápértékek a teljes elfogyasztott mennyiségre vonatkoznak. Ismeretlen értéket hagyj üresen.</p>`);return;}
    if(action==='archive-food'){await api.request(endpoint('food-logs/'+id),'DELETE',{});await refresh();return;}
    if(action==='new-daily'){dailyForm(dailyRows.find(d=>d.date===today));return;}
    if(action==='edit-daily'){dailyForm(dailyRows.find(d=>d.id===id));return;}
    if(action==='new-record'){recordForm(b.dataset.kind);return;}
    if(action==='edit-record'){recordForm(b.dataset.kind,records.find(r=>r.id===id));return;}
    if(action==='archive-record'){const r=records.find(r=>r.id===id);await api.request(endpoint('records/'+id),'DELETE',{kind:b.dataset.kind,version:r.version});await refresh();return;}
    if(action==='export'){const result={profile:await api.request(endpoint()),plans:await api.request(endpoint('plans')),workouts:[],restDays:await api.request(endpoint('rest-days')),measurements:await api.request(endpoint('measurements')),foodLogs:await api.request(endpoint('food-logs')),dailyLogs:await api.request(endpoint('daily-logs')),notes:await api.request(endpoint('notes'))};for(const w of await api.request(endpoint('workouts')))result.workouts.push(await api.request(endpoint('workouts/'+w.id)));for(const k of ['diet','medication','photo'])result[k]=await api.request(endpoint('records')+'?kind='+k);result.diets=await api.request(endpoint('diets'));result.foodCatalog=await api.request('/foods');const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`impavidus-${client.id}-${today}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Kliensadatok JSON-exportja elkészült.');return;}
  }catch(e){toast(e.message,true);}
});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='client-search'||el.id==='show-archived')filterClients();if(el.id==='exercise-search')document.querySelectorAll('[data-exercise-row]').forEach(row=>{row.hidden=!row.dataset.search.includes(el.value.toLowerCase());});if(el.id==='plan-exercise-search')$('#plan-exercise-select').querySelectorAll('option').forEach(option=>{option.hidden=!!option.value&&!option.textContent.toLowerCase().includes(el.value.toLowerCase());});});
document.addEventListener('change',event=>{const el=event.target;if(el.classList.contains('client-switch')){activeWorkout=null;route(page,el.value);}if(el.id==='performance-select')performanceChart();if(el.id==='show-archived')filterClients();});
function filterClients(){const q=$('#client-search').value.toLowerCase(),archived=$('#show-archived').checked;let count=0;document.querySelectorAll('[data-client-card]').forEach(c=>{c.hidden=!c.dataset.name.includes(q)||(!archived&&c.dataset.archived==='true');if(!c.hidden)count++;});$('#client-no-results').hidden=count>0;}
window.addEventListener('hashchange',()=>{activeWorkout=null;refresh();});
window.addEventListener('offline',()=>toast('Offline mód. A támogatott naplóadatok helyben mentődnek, és kapcsolódáskor szinkronizálódnak.',true));
window.addEventListener('online',()=>toast('A kapcsolat visszatért. A helyi mentések szinkronizációja elindult.'));
const observer=new MutationObserver(()=>{if($('#performance-chart')&&!$('#performance-chart').innerHTML)performanceChart();});observer.observe($('#app'),{childList:true,subtree:true});
window.addEventListener('impavidus-sync',()=>{if(user&&!hasUnsaved()&&!$('#dialog').open)refresh();else if(user)toast('A háttérszinkron elkészült. A nyitott adatbevitelt megőriztem; a nézet mentés után frissül.');});
function showUpdate(){if(waitingUpdate&&!$('#update-ready'))$('#app').insertAdjacentHTML('afterbegin',`<div id="update-ready" class="notice" role="status">Új alkalmazásverzió elérhető. ${button('apply-update','Frissítés alkalmazása')}</div>`);}
document.addEventListener('input',e=>{const form=e.target.closest('form');if(form)form.dataset.dirty='true';});
document.addEventListener('click',async e=>{if(e.target.closest('[data-action="apply-update"]')){if((await api.pending()).length||$('#dialog').open||hasUnsaved())return toast('Előbb mentsd a nyitott adatbevitelt és szinkronizáld a függő mentéseket.',true);waitingUpdate?.postMessage({type:'APPLY_UPDATE'});}});
document.addEventListener('click',e=>{if(e.target.closest('.nav a')&&hasUnsaved()&&!confirm('Van még nem mentett adatbevitel. Elhagyod az oldalt?'))e.preventDefault();},true);
window.addEventListener('beforeunload',e=>{if(hasUnsaved()){e.preventDefault();e.returnValue='';}});
if('serviceWorker'in navigator){navigator.serviceWorker.addEventListener('message',async e=>{if(e.data?.type==='CHECK_UPDATE'){let safe=false;try{safe=!(await api.pending()).length&&!$('#dialog').open&&!hasUnsaved();}catch{}e.source?.postMessage({type:'UPDATE_STATUS',nonce:e.data.nonce,safe});}if(e.data?.type==='UPDATE_BLOCKED')toast('Másik megnyitott lapon mentetlen adat van, vagy a lap nem válaszol. Mentsd az adatot, és zárd be a többi IMPAVIDUS-lapot a frissítéshez.',true);});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(waitingUpdate)location.reload();});navigator.serviceWorker.register('/sw.js').then(reg=>{const ready=()=>{if(reg.waiting&&navigator.serviceWorker.controller){waitingUpdate=reg.waiting;showUpdate();}};ready();reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',ready));}).catch(()=>toast('Az offline felület nem települt. Ellenőrizd a böngésző tárhelyengedélyeit.',true));}
refresh();
