import {nutritionChart} from './charts.js';
import {today as calendarDate} from './domain.mjs';
export function createModules(ctx){
  const {api,$,esc,num,dt,input,field,textarea,check,button,metric,head,lineChart,muscleChart,simpleForm,dialog,values,toast,refresh,shift,monday}=ctx;
  const state=()=>ctx.state(),isCoach=()=>['coach','admin'].includes(state().user?.role),canWrite=()=>!state().client?.archived_at,canFact=()=>state().user?.role==='client'&&canWrite();
  const path=r=>`/clients/${state().client.id}/${r}`,macros=['calories','protein','carbs','fat'],labels={calories:'Kalória',protein:'Fehérje',carbs:'Szénhidrát',fat:'Zsír'},unit=k=>k==='calories'?'kcal':'g';
  let date='',foods=[],diets=[],logs=[],nutrition=null,measurements=[],daily=[],meds=[],photos=[],dietBuilder=null,selectedWeek='';
  const selectDate=()=>`<label class="date-filter">${input('view_date','Dátum',date,'date',`id="module-date" required min="2000-01-01" max="${state().today}"`)}</label>`;
  const totalsBox=(sum,targets={},delta={})=>`<div class="metrics">${macros.map(k=>metric(labels[k],num(sum[k]),unit(k),`Cél: ${num(targets[k])} · Eltérés: ${num(delta[k])}`)).join('')}</div>`;
  const validMed=(m,d)=>(!m.data.start_date||m.data.start_date<=d)&&(!m.data.end_date||m.data.end_date>=d);
  const medList=items=>items.length?items.map(m=>`<div class="list-row"><div><h3>${esc(m.data.name)}</h3><p class="muted">${esc(m.data.dose)} ${esc(m.data.unit||'')} · ${esc(m.data.frequency||'Gyakoriság nincs megadva')}</p><p class="help">${esc(m.data.phase||'')} · ${dt(m.data.start_date)} – ${dt(m.data.end_date)}</p>${m.data.note?`<p class="note">${esc(m.data.note)}</p>`:''}</div><div class="actions">${button('history','Változástörténet',`data-entity="medication" data-id="${m.id}"`)}${isCoach()&&canWrite()?button('mod-edit-med','Szerkesztés',`data-id="${m.id}"`)+button('mod-archive-med','Archiválás',`data-id="${m.id}"`):''}</div></div>`).join(''):'<p class="muted">Nincs aktuális készítmény.</p>';
  function catalog(){return `<section class="card section-gap"><div class="row"><h2>Élelmiszer-katalógus</h2>${canWrite()?button('mod-new-food',isCoach()?'+ Élelmiszer':'+ Saját élelmiszer'):''}</div><input type="search" id="food-search" placeholder="Név vagy kategória…" aria-label="Élelmiszer keresése"><div class="table-wrap"><table><thead><tr><th>Élelmiszer / 100 g</th>${macros.map(k=>`<th>${labels[k]}</th>`).join('')}<th></th></tr></thead><tbody>${foods.map(f=>`<tr data-catalog-search="${esc((f.name+' '+f.category).toLowerCase())}"><td><strong>${esc(f.name)}</strong><div class="help">${esc(f.category)} · ${f.scope==='central'?'Központi':'Saját'} ${f.active?'':'· Inaktív'}</div></td>${macros.map(k=>`<td>${num(f[k])}</td>`).join('')}<td>${canWrite()&&(f.owner_id===state().user.id||isCoach()&&f.owner_id===null)?button('mod-edit-food','Szerkesztés',`data-id="${f.id}"`):''}</td></tr>`).join('')}</tbody></table></div>${!foods.length?'<p class="muted">A katalógus üres. Adj hozzá saját, ellenőrzött tápértékeket.</p>':''}<p class="help">Minden tápérték 100 grammra vonatkozik. A „—” ismeretlen érték, nem nulla.</p></section>`;}
  function foodForm(f={}){simpleForm(f.id?'Élelmiszer szerkesztése':'Új élelmiszer','mod-food',`<div class="form-grid">${input('name','Élelmiszer neve',f.name||'','text','required maxlength="160"')}${input('category','Kategória',f.category||'','text','maxlength="80"')}${macros.map(k=>field(k,labels[k]+' / 100 g',f[k],0,k==='calories'?1000:100)).join('')}${isCoach()?`<label>Katalógus<select name="scope" ${f.id?'disabled':''}><option value="central">Központi</option><option value="private" ${f.scope==='private'?'selected':''}>Saját</option></select></label>`:''}</div>${check('active','Aktív élelmiszer',f.active!==0)}<p class="help">Ismeretlen tápértéket hagyj üresen. A korábbi étkezések tápértéke megmarad.</p>`,`data-id="${f.id||''}"`);}
  function plannedTotals(items){return Object.fromEntries(macros.map(k=>[k,items.length&&items.every(i=>i[k]!=null)?items.reduce((n,i)=>n+i[k],0):null]));}
  function dietCard(d){return `<section class="card section-gap"><div class="row"><div><div class="eyebrow">${d.active?'Étrendterv':'Archivált terv'} · v${d.version}</div><h2>${esc(d.name)}</h2><p class="muted">${esc(state().client.name)} · ${esc(d.phase)} · ${dt(d.start_date)} – ${dt(d.end_date)} · ${d.meals} étkezés</p></div><div class="actions">${isCoach()&&canWrite()?button('mod-edit-diet','Szerkesztés',`data-id="${d.id}"`)+button('mod-copy-diet','Másolás',`data-id="${d.id}"`)+(d.active?button('mod-archive-diet','Archiválás',`data-id="${d.id}"`):''):''}${button('history','Változások',`data-entity="nutrition-plan" data-id="${d.id}"`)}</div></div><div class="metrics">${macros.map(k=>metric('Napi '+labels[k].toLowerCase()+'cél',num(d[k]),unit(k))).join('')}</div><h3>Tervezett ételek összesen</h3>${totalsBox(plannedTotals(d.items))}${Array.from({length:d.meals},(_,i)=>`<details class="meal-block" open><summary>${i+1}. étkezés</summary>${d.items.filter(x=>x.meal===i+1).map(x=>`<div class="list-row"><strong>${esc(x.name)}</strong><span class="muted">${num(x.grams)} g · ${num(x.calories)} kcal · F ${num(x.protein)} / CH ${num(x.carbs)} / Zs ${num(x.fat)}</span></div>`).join('')||'<p class="help">Nincs tervezett étel.</p>'}</details>`).join('')}${d.note?`<p class="note">${esc(d.note)}</p>`:''}</section>`;}
  function drawDiet(){const d=dietBuilder;dialog(d.id?'Étrend szerkesztése':'Új étrend',`<form data-form="mod-diet"><div class="form-grid">${input('name','Étrend neve',d.name,'text','required maxlength="160"')}${input('start_date','Kezdődátum',d.start_date,'date','required')}${input('end_date','Záródátum (opcionális)',d.end_date||'','date')}${input('phase','Étrendi fázis',d.phase||'','text','maxlength="120"')}${macros.map(k=>field(k,'Napi '+labels[k].toLowerCase()+'cél',d[k],0,20000)).join('')}<label>Étkezések száma<select name="meals"><option ${d.meals===5?'selected':''}>5</option><option ${d.meals===6?'selected':''}>6</option></select></label>${textarea('note','Megjegyzés',d.note||'','maxlength="10000"')}</div><div class="separator"></div><div class="toolbar"><label>Élelmiszer<input type="search" id="diet-food-search" placeholder="Étel keresése…"><select id="diet-food"><option value="">Válassz élelmiszert</option>${foods.filter(f=>f.active).map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('')}</select></label>${button('mod-diet-add','+ Tétel')}</div>${d.items.map((x,i)=>`<div class="diet-item" data-diet-item="${i}"><strong>${esc(x.name||foods.find(f=>f.id===x.food_id)?.name||'Étel')}</strong>${input('meal','Étkezés',x.meal,'number',`required min="1" max="${d.meals}" step="1"`)}${field('grams','Tervezett gramm',x.grams,0.1,10000,true)}${button('mod-diet-remove','×',`data-index="${i}" aria-label="Tétel eltávolítása"`)}</div>`).join('')}<div id="diet-preview" class="help"></div><p class="help">A terv külön adat; egyetlen tételt sem jelölünk automatikusan elfogyasztottnak.</p>${ctx.formFooter('Étrend mentése')}</form>`);}
  function captureDiet(){const f=$('#dialog form');if(!f)return;Object.assign(dietBuilder,values(f,macros.concat('meals')));dietBuilder.items=[...f.querySelectorAll('[data-diet-item]')].map(el=>({...dietBuilder.items[Number(el.dataset.dietItem)],meal:Number(el.querySelector('[name=meal]').value),grams:Number(el.querySelector('[name=grams]').value)}));}
  function foodLogForm(f={}){simpleForm(f.id?'Étkezés szerkesztése':'Étkezés rögzítése','mod-log',`<div class="form-grid">${input('date','Dátum',f.date||date,'date',`required max="${state().today}"`)}${input('meal','Étkezés sorszáma',f.meal||1,'number',`required min="1" max="${nutrition?.days[0]?.diet?.meals||state().client.preferences.meals}" step="1"`)}<label class="span">Élelmiszer keresése<input type="search" id="log-food-search" placeholder="Név alapján…"><select name="food_id" id="log-food-select"><option value="">Kézi bejegyzés</option>${foods.filter(x=>x.active||x.id===f.food_id).map(x=>`<option value="${x.id}" ${x.id===f.food_id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${input('name','Kézi étel neve',f.name||'','text','maxlength="160"')}${field('grams','Mennyiség (g)',f.grams||100,0.1,10000,true)}${macros.map(k=>field(k,'Kézi összes '+labels[k].toLowerCase(),f.food_id?null:f[k],0,20000)).join('')}</div><p class="help" id="log-calculation">Katalógusból választva a tápérték a grammokból számolódik.</p>${check('consumed','Ténylegesen elfogyasztottam',f.id?!!f.consumed:false)}${textarea('note','Megjegyzés',f.note||'','maxlength="2000"')}`,`data-id="${f.id||''}"`);updateLogCalculation();}
  function updateLogCalculation(){const f=$('[data-form="mod-log"]');if(!f)return;const catalogFood=foods.find(x=>x.id===f.elements.food_id.value),old=logs.find(x=>x.id===f.dataset.id),ref=old?.food_id===catalogFood?.id&&old?.reference?old.reference:catalogFood,g=Number(f.elements.grams.value);$('#log-calculation').textContent=ref?macros.map(k=>labels[k]+': '+num(ref[k]==null?null:ref[k]*g/100)+' '+unit(k)).join(' · '):'Kézi bejegyzésnél az egész elfogyasztott mennyiség tápértékét add meg.';for(const k of macros)f.elements[k].disabled=!!ref;f.elements.name.required=!ref;}
  function logList(){return logs.filter(f=>f.date===date).map(f=>`<article class="list-row"><div><h3>${esc(f.name)} · ${num(f.grams)} g</h3><div class="badge ${f.consumed?'good':'burgundy'}">${f.consumed?'Ténylegesen elfogyasztva':'Előkészítve · még nem fogyasztott'}</div><p class="muted">${f.meal}. étkezés · ${macros.map(k=>labels[k]+' '+num(f[k])+' '+unit(k)).join(' · ')}</p>${f.note?`<p class="note">${esc(f.note)}</p>`:''}</div>${canFact()?`<div class="actions">${!f.consumed?button('mod-consume','Elfogyasztottam',`data-id="${f.id}"`,true):''}${button('mod-edit-log','Szerkesztés',`data-id="${f.id}"`)}${button('mod-delete-log','Visszavonás',`data-id="${f.id}"`)}</div>`:''}</article>`).join('')||'<p class="muted">Erre a napra nincs étkezés.</p>';}
  function recoveryForm(d=null){const n=d?.data||{},p=state().client.preferences;simpleForm('Regeneráció és napi állapot','mod-daily',`<div class="form-grid">${input('date','Dátum',d?.date||date,'date',`required max="${state().today}" ${d?'readonly':''}`)}${field('sleep','Alvásórák',n.sleep,0,24)}${['sleep_quality','energy','stress','adherence'].map(k=>input(k,({sleep_quality:'Alvásminőség',energy:'Energia',stress:'Stressz',adherence:'Tervkövetés'})[k]+' · 1–5',n[k]??'','number','min="1" max="5" step="1"')).join('')}${input('pain_intensity','Fájdalom intenzitása · 0–10',n.pain_intensity??'','number','min="0" max="10" step="1"')}${input('pain','Fájdalom helye',n.pain||'','text','maxlength="2000"')}${input('digestion','Emésztés / székletállapot',n.digestion||'','text','maxlength="2000"')}${p.blood_pressure?input('blood_pressure','Vérnyomás',n.blood_pressure||''):''}${p.blood_glucose?field('blood_glucose','Vércukor',n.blood_glucose,0.1,50):''}${p.labs?input('lab_date','Vérkép dátuma',n.lab_date||'','date'):''}${p.water?field('water','Víz (liter)',n.water,0,20):''}${p.supplements?textarea('supplements','Étrend-kiegészítők',n.supplements||''):''}<div class="span">${textarea('note','Napi megjegyzés',n.note||'','maxlength="4000"')}${check('closed','Nap lezárása',!!d?.closed_at)}</div></div>`,`data-id="${d?.id||''}"`);}
  function medForm(m={}){const n=m.data||{};simpleForm('Készítmény és dózis','mod-med',`<div class="form-grid">${input('name','Készítmény neve',n.name||'','text','required maxlength="160"')}${input('dose','Dózis',n.dose||'','text','required maxlength="160"')}${input('unit','Mértékegység',n.unit||'','text','maxlength="30"')}${input('frequency','Időzítés / gyakoriság',n.frequency||'','text','maxlength="160"')}${input('phase','Fázis',n.phase||'','text','maxlength="120"')}${input('start_date','Kezdődátum',n.start_date||state().today,'date','required')}${input('end_date','Záródátum (opcionális)',n.end_date||'','date')}</div>${textarea('note','Megjegyzés',n.note||'','maxlength="2000"')}<p class="help">Nyilvántartás; nincs dózisszámítás vagy napi bevételjelölés.</p>`,`data-id="${m.id||''}"`);}
  function measurementForm(){simpleForm('Mérés rögzítése','mod-measure',`<div class="form-grid">${input('date','Mérés dátuma',date,'date',`required max="${state().today}"`)}${field('weight','Testsúly (kg)',null,20,500,true)}${Object.entries({waist:'Derék',chest:'Mellkas',hip:'Csípő',arm:'Kar',thigh:'Comb',shoulder:'Váll',calf:'Vádli'}).map(([k,label])=>field(k,label+' (cm)',null,1,300)).join('')}</div>${textarea('note','Megjegyzés','','maxlength="2000"')}<p class="help">Új mérésként kerül az előzményekbe; a korábbi mérés megmarad.</p>`);}
  async function page(name,parsed){
    if(!['diet','food','daily','medication','measurements','photos','settings','weekly'].includes(name)||!state().client)return null;
    date=parsed.searchParams.get('date')||date||state().today;
    if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||date>state().today)date=state().today;
    if(['diet','food','daily'].includes(name))[foods,diets,logs,nutrition]=await Promise.all([api.request('/foods'),api.request(path('diets')),api.request(path('food-logs')),api.request(path('nutrition')+`?from=${date}&to=${date}`)]);
    if(name==='diet'){const current=nutrition.days[0]?.diet;return head('Étrendlabor','Személyre szabott tervek, külön a tényleges fogyasztástól.',isCoach()&&canWrite()?button('mod-new-diet','+ Új étrend','',true):'')+selectDate()+`<p class="notice">Aktuális étrend: ${esc(current?.name||'Erre a napra nincs érvényes étrend')}.</p>`+diets.map(dietCard).join('')+catalog();}
    if(name==='food'){const d=nutrition.days[0];return head('Kajanapló','Grammokból számolt bevitel. Az előkészített étel csak megerősítés után tényadat.',canFact()?button('mod-new-log','+ Étkezés','',true):'')+selectDate()+totalsBox(d.actual,d.targets,d.delta)+`<section class="card"><div class="toolbar">${canFact()?button('mod-copy-meals','Étrend másolása','data-source="diet"')+button('mod-copy-meals','Előző nap másolása','data-source="previous"'):''}</div>${logList()}</section>`+catalog();}
    if(name==='medication'){meds=await api.request(path('records')+'?kind=medication');return head('Gyógyszernyilvántartás','Dátumozott dózislista és minden változás előzménye.',isCoach()&&canWrite()?button('mod-new-med','+ Készítmény','',true):'')+selectDate()+`<section class="card">${medList(meds)}<p class="help">A lejárt tételek is megmaradnak a listában és az előzményekben.</p></section>`;}
    if(name==='measurements'){measurements=await api.request(path('measurements'));return head('Mérések','Testsúly és körméretek, megőrzött történettel.',canWrite()?button('mod-new-measure','+ Mérés','',true):'')+`<div class="metrics">${metric('Kezdősúly',num(state().client.starting_weight),'kg')}${metric('Aktuális súly',num(state().client.metrics.current_weight),'kg')}${metric('Változás',num(state().client.metrics.weight_delta),'kg')}${metric('Változás aránya',num(state().client.metrics.weight_percent),'%')}</div><section class="card">${lineChart([...measurements].reverse().map(m=>({date:m.date,value:m.weight})),'Testsúly','kg')}<div class="table-wrap"><table><thead><tr>${['Dátum','Súly','Derék','Mellkas','Kar','Comb','Váll','Vádli','Megjegyzés'].map(x=>'<th>'+x+'</th>').join('')}</tr></thead><tbody>${measurements.map(m=>`<tr><td>${dt(m.date)}</td><td>${num(m.weight)}</td>${['waist','chest','arm','thigh','shoulder','calf'].map(k=>`<td>${num(m.data[k])}</td>`).join('')}<td>${esc(m.data.note||'')}</td></tr>`).join('')}</tbody></table></div></section>`;}
    if(name==='daily'){
      [daily,meds]=await Promise.all([api.request(path('daily-logs')),api.request(path('records')+'?kind=medication')]);const workouts=await api.request(path('workouts')),rests=await api.request(path('rest-days')),d=daily.find(d=>d.date===date),nutritionDay=nutrition.days[0],w=workouts.filter(w=>w.date===date&&w.status!=='archived');
      let sets=[];for(const workout of w)sets.push(...(await api.request(path('workouts/'+workout.id))).sets);
      return head('Napi napló','Regeneráció, edzés, kaja és készítmények egyetlen nézetben.')+selectDate()+`<div class="grid"><section class="card"><div class="eyebrow">01 · Regeneráció</div><h2>Napi állapot</h2>${d?`<dl class="detail-list">${Object.entries({sleep:'Alvásórák',sleep_quality:'Alvásminőség',energy:'Energia',stress:'Stressz',adherence:'Tervkövetés',digestion:'Emésztés',pain:'Fájdalom helye',pain_intensity:'Fájdalom 0–10',water:'Víz',supplements:'Kiegészítők'}).map(([k,l])=>`<div><dt>${l}</dt><dd>${esc(d.data[k]??'—')}</dd></div>`).join('')}</dl><p class="note">${esc(d.data.note||'')}</p><span class="badge">${d.closed_at?'Lezárt nap':'Nyitott nap'}</span>`:'<p class="muted">Még nincs napi állapot.</p>'}${canFact()?button('mod-daily','Állapot rögzítése / módosítása'):''}</section><section class="card"><div class="eyebrow">02 · Edzés</div><h2>${rests.some(r=>r.date===date)?'Pihenőnap':'Edzésállapot'}</h2>${w.map(w=>`<p>${esc(w.name)} · ${w.status==='completed'?'Lezárt':'Folyamatban'} · ${w.completed_sets} teljesített sorozat</p>`).join('')||'<p class="muted">Nincs edzésbejegyzés.</p>'}${sets.filter(s=>s.completed).map(s=>`<div class="help">${esc(s.exercise_name)} · ${num(s.actual_weight)} kg × ${num(s.actual_reps)} · RPE ${num(s.rpe)}</div>`).join('')}${button('go-workouts','Edzésnapló')}</section><section class="card span"><div class="eyebrow">03 · Kaja</div><h2>${esc(nutritionDay.diet?.name||'Nincs érvényes étrend')}</h2>${totalsBox(nutritionDay.actual,nutritionDay.targets,nutritionDay.delta)}${logList()}</section><section class="card span"><div class="eyebrow">04 · Gyógyszer</div><h2>Aktuális készítmények</h2>${medList(meds.filter(m=>validMed(m,date)))}</section></div>`;
    }
    if(name==='photos'){photos=(await api.request(path('records')+'?kind=photo')).sort((a,b)=>b.data.date.localeCompare(a.data.date));return head('Fotónapló','Privát képek, dátum szerint rendezve.',canFact()?button('new-record','+ Fotó','data-kind="photo"',true):'')+`<section class="card"><div class="toolbar"><label>Első időpont<select id="compare-first">${photos.map(p=>`<option value="${p.id}">${dt(p.data.date)}</option>`).join('')}</select></label><label>Második időpont<select id="compare-second">${photos.map((p,i)=>`<option value="${p.id}" ${i===1?'selected':''}>${dt(p.data.date)}</option>`).join('')}</select></label>${photos.length>=2?button('mod-compare','Összehasonlítás'):''}</div><div class="photo-grid">${photos.map(p=>`<article>${button('mod-zoom',`<img src="data:${esc(p.data.type)};base64,${p.data.base64}" alt="Fotó ${dt(p.data.date)}">`,`data-id="${p.id}" class="photo-open"`)}<h3>${dt(p.data.date)}</h3><p class="note">${esc(p.data.note||'')}</p>${canFact()?button('mod-photo-note','Dátum / megjegyzés',`data-id="${p.id}"`)+button('mod-archive-photo','Archiválás',`data-id="${p.id}"`):''}</article>`).join('')}</div>${photos.length?'':'<p class="muted">Még nincs fejlődési fotó.</p>'}</section>`;}
    if(name==='settings'){const s=await api.syncStatus();return head('Beállítások','Személyes beállítások, adatmentés és szinkronizáció.')+`<div class="grid"><section class="card"><h2>IMPAVIDUS LAB</h2><p>${esc(state().user.username)} · ${isCoach()?'Edző':'Kliens'}</p>${button('logout','Kijelentkezés')}<div class="separator"></div><h3>Kliens beállításai</h3><p class="help">Étkezések: ${state().client.preferences.meals} · Egészségmezők és kiegészítők</p>${canWrite()?button('mod-preferences','Beállítások módosítása'):''}${isCoach()&&canWrite()?button('edit-client','Profilbeállítások'):''}</section><section class="card"><h2>Mentés és szinkron</h2><p class="notice">${s.online?'Kapcsolat elérhető':'Offline mód'} · ${s.pending} helyi mentés vár szinkronra · ${s.conflicts} konfliktus</p>${button('mod-sync','Szinkronizálás')}${button('mod-sync-errors','Függő mentések / hibák')}${button('export','Kliensadatok JSON-exportja')}${isCoach()?button('mod-backup','Teljes helyi biztonsági mentés'):''}<p class="help">A helyi mentések ezen a böngészőprofilon, felhasználónként elkülönítve tárolódnak. Az automatikus mentések a szerver backups mappájába kerülnek.</p></section></div>`;}
    if(name==='weekly'){
      selectedWeek=parsed.searchParams.get('week')||monday(state().today);const to=shift(selectedWeek,6),stats=await api.request(path('statistics')+`?from=${selectedWeek}&to=${to}`),n=await api.request(path('nutrition')+`?from=${selectedWeek}&to=${to}`);[measurements,meds]=await Promise.all([api.request(path('measurements')),api.request(path('records')+'?kind=medication')]);const notes=await api.request(path('notes')),c=state().client;
      return head('Heti összesítő','Hétfőtől vasárnapig, tényleges adatokból.')+`<div class="toolbar">${button('prev-week','← Előző hét',`data-week="${selectedWeek}"`)}<span>${dt(selectedWeek)} – ${dt(to)}</span>${button('next-week','Következő hét →',`data-week="${selectedWeek}" ${selectedWeek>=monday(state().today)?'disabled':''}`)}${button('mod-export-week','CSV','data-format="csv"')}${button('mod-export-week','XLSX','data-format="xlsx"')}</div><div class="metrics">${metric('Teljesített nap',n.days.filter(d=>c.metrics.activity.completed_dates.includes(d.date)).length,'/ 7')}${metric('Aktuális sorozat',c.metrics.activity.current,'nap')}${metric('Leghosszabb sorozat',c.metrics.activity.longest,'nap')}${metric('Átlagos kalória',num(n.averages.calories),'kcal')}${metric('Átlagos fehérje',num(n.averages.protein),'g')}${metric('Volumen',num(stats.volume),'kg')}${metric('Keménysorozat',stats.hardSets,'')}${metric('Átlagos RPE',num(stats.averageRpe),'')}</div><div class="grid"><section class="card"><h2>Testsúly</h2>${lineChart([...measurements].reverse().map(m=>({date:m.date,value:m.weight})),'Testsúly','kg')}</section><section class="card"><h2>Súlyváltozás</h2>${lineChart([...measurements].reverse().map(m=>({date:m.date,value:c.starting_weight==null?null:m.weight-c.starting_weight})),'Súlyváltozás','kg')}</section><section class="card"><h2>Napi kalória</h2>${nutritionChart(n.days,'calories','Kalória','kcal',esc,num,dt)}</section><section class="card"><h2>Napi makrók és célok</h2>${['protein','carbs','fat'].map(k=>`<h3>${labels[k]}</h3>${nutritionChart(n.days,k,labels[k],'g',esc,num,dt)}`).join('')}<div class="table-wrap"><table><thead><tr><th>Nap</th><th>Kalória / cél</th><th>F / cél</th><th>CH / cél</th><th>Zs / cél</th></tr></thead><tbody>${n.days.map(d=>`<tr><td>${dt(d.date)}</td>${macros.map(k=>`<td>${num(d.actual[k])} / ${num(d.targets[k])}<div class="help">Δ ${num(d.delta[k])}</div></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="help">Az átlag a kajanaplóval rendelkező napokra számolódik. Ismeretlen tápértékből nem készítünk becslést.</p></section><section class="card"><h2>Sorozatok izomcsoportonként</h2>${muscleChart(stats.muscle)}</section><section class="card"><h2>Edzésvolumen</h2>${lineChart(stats.series.map(s=>({date:s.date,value:s.volume})),'Volumen','kg')}</section><section class="card"><h2>Fejlődési megjegyzések</h2>${notes.filter(n=>{const date=calendarDate(api.timeZone,new Date(n.created_at));return date>=selectedWeek&&date<=to;}).map(n=>`<p class="note">${esc(n.text)}</p>`).join('')||'<p class="muted">Ezen a héten nincs megjegyzés.</p>'}${isCoach()&&canWrite()?button('new-note','+ Megjegyzés'):''}</section><section class="card"><h2>Aktuális készítmények</h2>${medList(meds.filter(m=>validMed(m,state().today)))}</section></div>`;
    }
  }
  async function action(action,b){
    if(!action.startsWith('mod-'))return false;const id=b.dataset.id;
    if(action==='mod-new-food')foodForm();
    if(action==='mod-edit-food')foodForm(foods.find(f=>f.id===id));
    if(action==='mod-new-diet'){dietBuilder={name:'',start_date:state().today,end_date:null,phase:'',meals:state().client.preferences.meals,items:[]};drawDiet();}
    if(action==='mod-edit-diet'){dietBuilder=structuredClone(diets.find(d=>d.id===id));drawDiet();}
    if(action==='mod-diet-add'){captureDiet();const f=foods.find(f=>f.id===$('#diet-food').value);if(!f)throw new Error('Válassz élelmiszert.');dietBuilder.items.push({food_id:f.id,name:f.name,grams:100,meal:1});drawDiet();}
    if(action==='mod-diet-remove'){captureDiet();dietBuilder.items.splice(Number(b.dataset.index),1);drawDiet();}
    if(action==='mod-archive-diet'){const d=diets.find(d=>d.id===id);await api.request(path('diets/'+id),'DELETE',{version:d.version});await refresh();}
    if(action==='mod-copy-diet'){const d=diets.find(d=>d.id===id);simpleForm('Étrend másolása','mod-copy-diet',input('name','Új név',d.name+' — másolat','text','required')+input('start_date','Kezdődátum',state().today,'date','required')+`<label>Célkliens<select name="client_id">${state().clients.filter(c=>!c.archived_at).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label>`,`data-id="${id}"`);}
    if(action==='mod-new-log')foodLogForm();if(action==='mod-edit-log')foodLogForm(logs.find(f=>f.id===id));
    if(action==='mod-consume'){const f=logs.find(f=>f.id===id);await api.request(path('food-logs/'+id),'PATCH',{version:f.version,consumed:true});await refresh();toast(api.lastPending?'Helyben jelölve · szinkronra vár.':'Tényleges fogyasztás mentve.');}
    if(action==='mod-delete-log'){const f=logs.find(f=>f.id===id);await api.request(path('food-logs/'+id),'DELETE',{version:f.version});await refresh();}
    if(action==='mod-copy-meals'){await api.request(path('food-logs/copy'),'POST',{date,source:b.dataset.source,from_date:shift(date,-1)});await refresh();toast('Tételek előkészítve. Még egyik sincs elfogyasztottnak jelölve.');}
    if(action==='mod-daily')recoveryForm(daily.find(d=>d.date===date));
    if(action==='mod-new-med')medForm();if(action==='mod-edit-med')medForm(meds.find(m=>m.id===id));
    if(action==='mod-archive-med'){const m=meds.find(m=>m.id===id);await api.request(path('records/'+id),'DELETE',{kind:'medication',version:m.version});await refresh();}
    if(action==='mod-new-measure')measurementForm();
    if(action==='mod-zoom'){const p=photos.find(p=>p.id===id);dialog('Fotó · '+dt(p.data.date),`<img class="photo-large" src="data:${p.data.type};base64,${p.data.base64}" alt="Fotó ${dt(p.data.date)}"><p class="note">${esc(p.data.note||'')}</p>`);}
    if(action==='mod-compare'){const a=photos.find(p=>p.id===$('#compare-first').value),b=photos.find(p=>p.id===$('#compare-second').value);dialog('Időpontok összehasonlítása',`<div class="photo-compare">${[a,b].map(p=>`<figure><img src="data:${p.data.type};base64,${p.data.base64}" alt="Fotó ${dt(p.data.date)}"><figcaption>${dt(p.data.date)}</figcaption></figure>`).join('')}</div>`);}
    if(action==='mod-photo-note'){const p=photos.find(p=>p.id===id);simpleForm('Fotó adatai','mod-photo',input('date','Dátum',p.data.date,'date',`required max="${state().today}"`)+textarea('note','Megjegyzés',p.data.note||''),`data-id="${id}"`);}
    if(action==='mod-archive-photo'){const p=photos.find(p=>p.id===id);await api.request(path('records/'+id),'DELETE',{kind:'photo',version:p.version});await refresh();}
    if(action==='mod-preferences'){const p=state().client.preferences;simpleForm('Kliens beállításai','mod-preferences',`<label>Étkezések száma<select name="meals"><option ${p.meals===5?'selected':''}>5</option><option ${p.meals===6?'selected':''}>6</option></select></label>`+Object.entries({blood_pressure:'Vérnyomás',blood_glucose:'Vércukor',labs:'Vérkép dátuma',water:'Vízfogyasztás',supplements:'Étrend-kiegészítők'}).map(([k,l])=>check(k,l,p[k])).join(''));}
    if(action==='mod-backup'){const result=await api.request('/maintenance/backup','POST',{});toast('Biztonsági mentés elkészült: '+result.filename);}
    if(action==='mod-sync'){await api.sync();await refresh();toast('Szinkronizáció ellenőrizve.');}
    if(action==='mod-sync-errors'){const rows=await api.pending();dialog('Helyi mentések és szinkronhibák',rows.map(r=>`<section class="revision"><strong>${esc(r.method+' '+r.path)}</strong><p>${esc(r.error||'Szinkronizálásra vár')}</p><p class="help">${dt(r.created_at)}</p>${r.error?button('mod-conflict-export','Mentés exportálása',`data-id="${r.key}"`)+button('mod-conflict-resolve','Összevetés a szerverrel',`data-id="${r.key}"`)+button('mod-conflict-server','Szerver adatát megtartom',`data-id="${r.key}"`):''}</section>`).join('')||'<p>Nincs függő mentés.</p>');}
    if(action==='mod-conflict-export'){const r=(await api.pending()).find(r=>r.key===id);download(JSON.stringify(r,null,2),'impavidus-helyi-mentes.json','application/json');}
    if(action==='mod-conflict-resolve'){const r=(await api.pending()).find(r=>r.key===id),server=await api.serverState(r);dialog('Ütköző adatok összevetése',`<h3>Helyi módosítás</h3><pre class="export">${esc(JSON.stringify(r.data,null,2))}</pre><h3>Szerver jelenlegi adata</h3><pre class="export">${esc(JSON.stringify(server,null,2))}</pre><p class="help">A helyi mentés megmarad. A szerverre csak a választásod után kerül új módosítás.</p>${button('mod-conflict-retry','Helyi módosítás újraküldése',`data-id="${id}"`,true)}${button('mod-conflict-server','Szerver adatát megtartom',`data-id="${id}"`)}${button('mod-conflict-export','Helyi mentés exportja',`data-id="${id}"`)}`);}
    if(action==='mod-conflict-retry'){await api.resolve(id,'local');$('#dialog').close();await refresh();}
    if(action==='mod-conflict-server'){await api.resolve(id,'server');$('#dialog').close();await refresh();}
    if(action==='mod-export-week'){if((await api.pending()).length)throw new Error('Heti export előtt szinkronizáld vagy rendezd a függő helyi mentéseket.');const r=await api.request(path('export')+`?week=${selectedWeek}&format=${b.dataset.format}`);download(Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0)),r.name,r.type);}
    return true;
  }
  function download(data,name,type){const blob=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async function submit(kind,f){if(!kind.startsWith('mod-'))return false;const id=f.dataset.id;
    if(kind==='mod-food'){const old=foods.find(x=>x.id===id);await api.request('/foods'+(id?'/'+id:''),id?'PATCH':'POST',{...values(f,macros,['active']),version:old?.version});}
    if(kind==='mod-diet'){captureDiet();await api.request(path('diets'+(dietBuilder.id?'/'+dietBuilder.id:'')),dietBuilder.id?'PATCH':'POST',dietBuilder);dietBuilder=null;}
    if(kind==='mod-copy-diet')await api.request(path('diets/'+id+'/copy'),'POST',values(f));
    if(kind==='mod-log'){const old=logs.find(x=>x.id===id);await api.request(path('food-logs'+(id?'/'+id:'')),id?'PATCH':'POST',{...values(f,['grams','meal',...macros],['consumed']),version:old?.version});}
    if(kind==='mod-daily'){const old=daily.find(x=>x.id===id),n=values(f,['sleep','sleep_quality','energy','stress','adherence','pain_intensity','blood_glucose','water'],['closed']);for(const k of ['blood_pressure','blood_glucose','lab_date','water','supplements'])if(!f.elements[k]&&old)n[k]=old.data[k];await api.request(path('daily-logs'),'POST',{...n,version:old?.version});}
    if(kind==='mod-med'){const old=meds.find(x=>x.id===id),data=values(f);if(data.end_date&&data.end_date<data.start_date)throw new Error('A záródátum nem előzheti meg a kezdést.');await api.request(path('records'+(id?'/'+id:'')),id?'PATCH':'POST',{kind:'medication',data,version:old?.version});}
    if(kind==='mod-measure')await api.request(path('measurements'),'POST',values(f,['weight','waist','chest','hip','arm','thigh','shoulder','calf']));
    if(kind==='mod-photo'){const p=photos.find(p=>p.id===id);await api.request(path('records/'+id),'PATCH',{kind:'photo',version:p.version,data:{...p.data,...values(f)}});}
    if(kind==='mod-preferences')await api.request(path('preferences'),'PATCH',{...values(f,['meals'],['blood_pressure','blood_glucose','labs','water','supplements']),version:state().client.version});
    return true;
  }
  document.addEventListener('input',e=>{const el=e.target;if(el.id==='food-search')document.querySelectorAll('[data-catalog-search]').forEach(row=>row.hidden=!row.dataset.catalogSearch.includes(el.value.toLowerCase()));if(el.id==='diet-food-search'||el.id==='log-food-search'){const select=$(el.id==='diet-food-search'?'#diet-food':'#log-food-select');select.querySelectorAll('option').forEach(o=>o.hidden=!!o.value&&!o.textContent.toLowerCase().includes(el.value.toLowerCase()));}if(el.closest('[data-form="mod-diet"]')){captureDiet();const items=dietBuilder.items.map(i=>{const ref=foods.find(f=>f.id===i.food_id);return Object.fromEntries(macros.map(k=>[k,ref?.[k]==null?null:ref[k]*i.grams/100]));}),sum=plannedTotals(items),preview=$('#diet-preview');if(preview)preview.textContent='Tervezett összesen: '+macros.map(k=>labels[k]+' '+num(sum[k])+' '+unit(k)).join(' · ');}if(el.closest('[data-form="mod-log"]'))updateLogCalculation();});
  document.addEventListener('change',e=>{if(e.target.id==='module-date'){const p=new URLSearchParams(location.hash.split('?')[1]);p.set('date',e.target.value);location.hash=location.hash.split('?')[0]+'?'+p;}if(e.target.closest('[data-form="mod-log"]'))updateLogCalculation();});
  return {page,action,submit};
}
