'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{Store}=require('../backend/store'),{restore}=require('../backend/restore');
test('teljes mentés-visszaállítás: fotó, tartós adat, előző adatbázis, session törlés',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'impavidus-restore-')),file=path.join(dir,'live.sqlite'),store=new Store(file),now=new Date().toISOString(),epoch=store.get('SELECT value FROM app_meta WHERE key=?','database_epoch').value;let saved;
 try{store.run('INSERT INTO accounts(id,username,role,created_at) VALUES(?,?,?,?)','a','synthetic-restore','client',now);store.run('INSERT INTO clients(id,account_id,name,start_date,created_at,updated_at) VALUES(?,?,?,?,?,?)','c','a','Mentett sportoló','2026-10-03',now,now);store.run('INSERT INTO records VALUES(?,?,?,?,1,?,?,NULL)','photo','c','photo',JSON.stringify({date:'2026-10-03',base64:'synthetic-image-bytes',type:'image/png'}),now,now);store.run('INSERT INTO sessions VALUES(?,?,?,?)','synthetic-hash','a','synthetic-csrf','2099-01-01T00:00:00Z');store.run('INSERT INTO mutation_receipts VALUES(?,?,?,?,?,?,?,?)','a','synthetic-key','POST','/synthetic','synthetic-digest',201,'{}',now);saved=await require('../backend/backups').save(store,{directory:path.join(dir,'snapshots')});store.run('UPDATE clients SET name=? WHERE id=?','Mentés utáni módosítás','c');}finally{store.close();}
 await assert.rejects(restore(saved.path,file,{isRunning:()=>true}),/állítsd le/);const result=await restore(saved.path,file),restored=new Store(file),before=new Store(result.safety);
 try{assert.equal(restored.get('SELECT name FROM clients WHERE id=?','c').name,'Mentett sportoló');assert.equal(before.get('SELECT name FROM clients WHERE id=?','c').name,'Mentés utáni módosítás');assert.equal(JSON.parse(restored.get('SELECT data_json FROM records WHERE id=?','photo').data_json).base64,'synthetic-image-bytes');assert.equal(before.get('SELECT count(*) AS n FROM sessions').n,1);assert.equal(restored.get('SELECT count(*) AS n FROM sessions').n,0);assert.equal(restored.get('SELECT count(*) AS n FROM mutation_receipts').n,0);assert.notEqual(restored.get('SELECT value FROM app_meta WHERE key=?','database_epoch').value,epoch);assert.equal(restored.get('PRAGMA integrity_check').integrity_check,'ok');}finally{restored.close();before.close();}
 const corrupt=path.join(dir,'corrupt.sqlite');fs.writeFileSync(corrupt,'not a database');await assert.rejects(restore(corrupt,file));const intact=new Store(file);try{assert.equal(intact.get('SELECT name FROM clients WHERE id=?','c').name,'Mentett sportoló');}finally{intact.close();}
});
test('automatikus mentési megőrzés csak auto fájlokra vonatkozik',async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'impavidus-retention-')),store=new Store(':memory:'),old=process.env.BACKUP_KEEP;process.env.BACKUP_KEEP='1';fs.writeFileSync(path.join(dir,'auto-2000-01-01T00-00-00-000Z.sqlite'),'old');fs.writeFileSync(path.join(dir,'manual-2000.sqlite'),'keep');try{await require('../backend/backups').save(store,{automatic:true,directory:dir});assert.equal(fs.readdirSync(dir).filter(f=>f.startsWith('auto-')).length,1);assert.ok(fs.existsSync(path.join(dir,'manual-2000.sqlite')));}finally{store.close();if(old===undefined)delete process.env.BACKUP_KEEP;else process.env.BACKUP_KEEP=old;}
});
