'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createServer,staticPath}=require('../backend/server'),{Store}=require('../backend/store');
test('publikus allowlist kizárja a privát fájlokat, archív demót és útvonalkitörést',()=>{for(const p of ['/index.html','/icon.svg','/frontend/app.js','/frontend/styles.css'])assert.ok(staticPath(p));for(const p of ['/.env','/backend/app.js','/db/sqlite/001_core.sql','/data/impavidus.sqlite','/legacy/step2-index.html','/%2e%2e/outside.txt','/frontend/%2e%2e/backend/app.js'])assert.equal(staticPath(p),null);});
test('valós SQLite és munkamenet állapot, CSP és tíz menüoldal',async t=>{const logs=[],store=new Store(':memory:'),server=createServer({store,logger:{info:s=>logs.push(JSON.parse(s)),error(){}}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));store.close();});const base=`http://127.0.0.1:${server.address().port}`;
  const health=await fetch(base+'/api/v1/health');assert.equal(health.status,200);assert.equal((await health.json()).database,'sqlite');assert.equal((await fetch(base+'/api/v1/ready')).status,200);
  const session=await(await fetch(base+'/api/v1/auth/session')).json();assert.equal(session.setupRequired,true);assert.equal(session.user,null);assert.equal((await fetch(base+'/api/v1/clients')).status,401);
  const page=await fetch(base);assert.equal(page.status,200);assert.match(page.headers.get('content-security-policy'),/script-src 'self'/);assert.match(await page.text(),/Alex team/);
  const js=await(await fetch(base+'/frontend/app.js')).text();for(const name of ['Adatlap','Napi napló','Heti összesítő','Edzésnapló','Étrend','Kajanapló','Gyógyszer','Mérések','Fotónapló','Beállítások'])assert.ok(js.includes(name));
  assert.equal((await fetch(base+'/manifest.webmanifest')).status,200);assert.equal((await fetch(base+'/backend/app.js')).status,400);assert.ok(logs.every(e=>e.route&&e.status));
  const http=require('node:http');const hostStatus=await new Promise((resolve,reject)=>{http.get(base+'/api/v1/health',{headers:{Host:'evil.example:123'}},r=>{r.resume();resolve(r.statusCode);}).on('error',reject);});assert.equal(hostStatus,421);
});
